/**
 * Curator display-metadata overrides (researched + verified, 2026-05-31).
 *
 * Keyed by curator address (0x lowercased, or tc:<slug>). Corrects entity names
 * (stripping vault/chain qualifiers), official website + X handle, logo (unavatar.io
 * from the verified handle), description, and entity details. Applied to the DB by
 * scripts/apply-curator-overrides.ts. Durable: the collectors do not overwrite these
 * fields (names here are not auto-generated; website/twitter/logo/desc are untouched).
 */

export interface CuratorOverride {
  name?: string;
  website?: string;
  twitter?: string;
  logoUrl?: string;
  description?: string;
  entityType?: string;
  jurisdiction?: string;
  foundedYear?: number;
}

export const CURATOR_OVERRIDES: Record<string, CuratorOverride> = {
  "0x9e396de3312d373b87f9bd8763fb48184b42aac0": {"website":"https://sentora.com","twitter":"SentoraHQ","logoUrl":"https://unavatar.io/x/SentoraHQ","description":"Sentora is an institutional DeFi platform and one of the largest public DeFi vault curators, formed in 2025 from the merger of analytics firm IntoTheBlock and Trident Digital.","entityType":"Corporation","jurisdiction":"British Virgin Islands","foundedYear":2025},
  "0x827e86072b06674a077f592a531dce4590adecdb": {"website":"https://www.steakhouse.financial","twitter":"SteakhouseFi","logoUrl":"https://unavatar.io/x/SteakhouseFi","description":"Steakhouse Financial is a DeFi advisory and research firm that curates institutional-grade yield vaults, acting as the largest vault curator on the Morpho lending protocol.","entityType":"LLC","jurisdiction":"Cayman Islands","foundedYear":2023},
  "tc:midas": {"website":"https://midas.app","twitter":"MidasRWA","logoUrl":"https://unavatar.io/x/MidasRWA","description":"Midas is a tokenization platform that issues institutional-grade investment products as ERC-20 tokens (such as mTBILL Treasury Bills and mF-ONE private credit), many of which are deployed and curated across DeFi lending protocols including Morpho.","entityType":"Corporation","jurisdiction":"Germany","foundedYear":2023},
  "0x9e33faae38ff641094fa68c65c2ce600b3410585": {"website":"https://www.gauntlet.xyz","twitter":"gauntlet_xyz","logoUrl":"https://unavatar.io/x/gauntlet_xyz","description":"Gauntlet is a quantitative risk-management and optimization firm for DeFi that runs simulation-based risk modeling and curates yield/vault strategies across protocols such as Morpho.","entityType":"Corporation","jurisdiction":"United States","foundedYear":2018},
  "0x3f32bc09d41ee699844f8296e806417d6bf61bba": {"name":"Sky","website":"https://sky.money","twitter":"SkyEcosystem","logoUrl":"https://unavatar.io/x/SkyEcosystem","description":"Sky (formerly MakerDAO) is a decentralized finance protocol governed by SKY token holders that issues the USDS stablecoin and operates the sky.money curator on Morpho and other lending protocols.","entityType":"DAO","jurisdiction":"Decentralized","foundedYear":2015},
  "tc:telosc": {"name":"TelosC","website":"https://telosc.com","twitter":"TelosConsilium","logoUrl":"https://unavatar.io/x/TelosConsilium","description":"Telos Consilium is a Swiss DeFi risk-curation and advisory firm that designs and manages curated lending vaults (under its \"TelosC\" brand) and provides collateral risk management and parameter optimization for protocols such as Morpho and Euler.","entityType":"Corporation","jurisdiction":"Switzerland","foundedYear":2024},
  "tc:curvance": {"website":"https://curvance.com","twitter":"Curvance","logoUrl":"https://unavatar.io/x/Curvance","description":"Curvance is a modular cross-chain DeFi lending protocol that lets users deposit crypto collateral, borrow against it, and earn yield on yield-bearing assets through a unified interface.","entityType":"Corporation","foundedYear":2022},
  "0x6788c8ad65e85cca7224a0b46d061ef7d81f9da5": {"website":"https://alphaping.ch","twitter":"0xAlphaping","logoUrl":"https://unavatar.io/x/0xAlphaping","description":"AlphaPing is a Swiss-based DeFi vault curator and on-chain credit operator that designs and manages non-custodial, mandate-driven ERC-4626 lending vaults on protocols including Morpho, Euler, and IPOR.","entityType":"LLC","jurisdiction":"Switzerland","foundedYear":2017},
  "0xa13094eced689b7419baba12851374424c1486f1": {"name":"Galaxy Digital","website":"https://www.galaxy.com","twitter":"galaxyhq","logoUrl":"https://unavatar.io/x/galaxyhq","description":"Galaxy Digital is a publicly traded (Nasdaq/TSX: GLXY) digital assets and data center infrastructure firm offering institutional trading, asset management, and lending services in crypto and AI infrastructure.","entityType":"Corporation","jurisdiction":"United States","foundedYear":2018},
  "tc:sierra": {"website":"https://sierra.money","twitter":"SierraIsMoney","logoUrl":"https://unavatar.io/x/SierraIsMoney","description":"Sierra (Sierra Protocol) is the issuer of SIERRA, a Liquid Yield Token whose reserves are deployed across real-world assets and blue-chip DeFi yield sources, including onchain lending vaults.","entityType":"Foundation","jurisdiction":"Cayman Islands"},
  "0x4687e45bb5518a995913a24bb2816fe2031d74d8": {"name":"Wintermute","website":"https://www.wintermute.com","twitter":"wintermute_t","logoUrl":"https://unavatar.io/x/wintermute_t","description":"Wintermute is a London-based algorithmic trading firm and crypto market maker that provides liquidity across centralized and decentralized markets and curates DeFi lending vaults through its Armitage product on Morpho.","entityType":"Corporation","jurisdiction":"United Kingdom","foundedYear":2017},
  "tc:k3-capital": {"website":"https://k3.capital","twitter":"k3_capital","logoUrl":"https://unavatar.io/x/k3_capital","description":"K3 Capital is an institutional DeFi asset and risk management firm running non-directional, delta-neutral yield strategies and curating lending vaults across protocols including Morpho, Euler, and Gearbox.","entityType":"Corporation","foundedYear":2021},
  "tc:yo": {"website":"https://www.yo.xyz","twitter":"yield","logoUrl":"https://unavatar.io/x/yield","description":"YO is a multi-chain DeFi yield optimizer that automatically allocates and rebalances deposits across lending markets, liquidity pools, and yield-bearing tokens on chains including Ethereum, Base, and Solana to deliver risk-adjusted yield.","entityType":"Corporation","jurisdiction":"United States","foundedYear":2025},
  "0xc266b1181a80e84edc2c6596718e88e8115c1eaa": {"name":"KPK","website":"https://kpk.io","twitter":"kpk_io","logoUrl":"https://unavatar.io/x/kpk_io","description":"kpk (formerly karpatkey) is a non-custodial onchain asset manager that curates DeFi vaults and manages treasuries for leading protocols and DAOs, including agent-powered vaults on Morpho.","entityType":"Corporation","jurisdiction":"Cayman Islands","foundedYear":2020},
  "clearstar": {"website":"https://www.clearstar.xyz","twitter":"ClearstarLabs","logoUrl":"https://unavatar.io/x/ClearstarLabs","description":"Clearstar Labs AG is a Swiss blockchain advisory and infrastructure provider that acts as an onchain risk curator, deploying and managing institutional-grade yield vaults across DeFi lending protocols including Morpho and Euler.","entityType":"Corporation","jurisdiction":"Switzerland","foundedYear":2022},
  "tc:altura": {"website":"https://altura.trade","twitter":"alturax","logoUrl":"https://unavatar.io/x/alturax","description":"Altura is a multi-strategy DeFi yield protocol on HyperEVM that allocates user deposits across non-directional, institutional-grade trading strategies including market making, funding-rate and basis arbitrage, and real-world-asset (gold) trading, and acts as a vault curator across Morpho and other protocols.","entityType":"Corporation","foundedYear":2025},
  "0xa817e31c4b9b3a5a596bb2e81d5068030b1778ec": {"name":"Flowdesk","website":"https://www.flowdesk.co","twitter":"flowdesk_co","logoUrl":"https://unavatar.io/x/flowdesk_co","description":"Flowdesk is a France-based, AMF-registered digital asset trading and technology firm providing market making, OTC trading, and DeFi liquidity strategies, including curated vaults on Morpho.","entityType":"Corporation","jurisdiction":"France","foundedYear":2020},
  "0xbbacdcfb9691dfa1066ab29edfcc4a73f6def918": {"website":"https://rockawayx.com","twitter":"Rockaway_X","logoUrl":"https://unavatar.io/x/Rockaway_X","description":"RockawayX is a Prague-based digital asset investment and engineering firm (~$2B AUM) that does venture investing, infrastructure/validator operation, and on-chain liquidity provision, and curates lending vaults on Morpho.","entityType":"LLC","jurisdiction":"Czech Republic","foundedYear":2018},
  "0x75178137d3b4b9a0f771e0e149b00fb8167ba325": {"website":"https://www.hyperithm.com","twitter":"hyperithm","logoUrl":"https://unavatar.io/x/hyperithm","description":"Hyperithm is a digital asset management firm based in Tokyo and Seoul, active in algorithmic/quant trading, DeFi vault curation, and venture investments.","entityType":"Corporation","jurisdiction":"Japan and South Korea","foundedYear":2018},
  "0xa81ae7d57d68fd6ef76a3082134bd2f3019aec24": {"website":"https://www.augustdigital.io","twitter":"august_digital","logoUrl":"https://unavatar.io/x/august_digital","description":"August (also known as August Digital, formerly Fractal) is an institutional crypto prime brokerage that provides on-chain smart-contract accounts, risk engines, and execution tools connecting institutions to DeFi protocols such as Morpho, Aave, and Uniswap.","entityType":"Corporation","jurisdiction":"United States","foundedYear":2023},
  "0x8257dd8e97aa1e903339e3ff45240162fe342132": {"website":"https://avantgarde.finance","twitter":"avantgardefi","logoUrl":"https://unavatar.io/x/avantgardefi","description":"Avantgarde Finance is a DeFi-native digital asset management, advisory, and research firm that curates on-chain vault strategies (including Morpho vaults) and manages treasury assets for DAOs, foundations, and institutional investors.","entityType":"Corporation","jurisdiction":"United Kingdom","foundedYear":2018},
  "tc:termmax": {"name":"TermMax","website":"https://ts.finance","twitter":"TermMaxFi","logoUrl":"https://unavatar.io/x/TermMaxFi","description":"Term Structure Labs is the Hong Kong-based developer of TermMax, a fixed-rate borrowing and lending DeFi protocol that runs ERC-4626 vaults (including as a Morpho curator) across Ethereum, Arbitrum, and BNB Chain.","entityType":"Corporation","jurisdiction":"Hong Kong","foundedYear":2022},
  "0xf930ebbd05ef8b25b1797b9b2109ddc9b0d43063": {"name":"StakeDAO","website":"https://www.stakedao.org","twitter":"StakeDAOHQ","logoUrl":"https://unavatar.io/x/StakeDAOHQ","description":"StakeDAO is a non-custodial DeFi protocol, launched in 2021, known for its Liquid Lockers and curated yield vaults built on top of governance-token staking infrastructure (Curve, Pendle, Balancer, and others).","entityType":"DAO","foundedYear":2021},
  "0x1280e86cd7787ffa55d37759c0342f8cd3c7594a": {"website":"https://www.yieldnest.finance","twitter":"YieldNestFi","logoUrl":"https://unavatar.io/x/YieldNestFi","description":"YieldNest is a DeFi protocol that builds liquid restaking and real-world-asset yield tokens (MAX LRTs/vaults) which bundle multiple curated strategies into single composable assets, also offering Vault-as-a-Service infrastructure to third parties.","entityType":"Corporation","jurisdiction":"Singapore","foundedYear":2023},
  "tc:9summits": {"website":"https://9summits.io","twitter":"nine_summits","logoUrl":"https://unavatar.io/x/nine_summits","description":"9Summits is a DeFi asset management firm that curates and operates yield-bearing vaults on protocols such as Morpho."},
  "0xd3fd4f95820a9aa848ce716d6c200eaefb9a2e49": {"name":"Fiber"},
  "0x24db7c6f689e480d6e5d45dad400cc4456c832f0": {"name":"API3","website":"https://api3.org","twitter":"api3dao","logoUrl":"https://unavatar.io/x/api3dao","description":"API3 is a decentralized oracle protocol providing first-party data feeds (dAPIs) and OEV services to blockchain applications, governed by the API3 DAO and operating as a Morpho vault curator since December 2025.","entityType":"DAO","jurisdiction":"Cayman Islands","foundedYear":2020},
  "0x72882eb5d27c7088dfa6dde941dd42e5d184f0ef": {"website":"https://re7.capital/","twitter":"Re7Capital","logoUrl":"https://unavatar.io/x/Re7Capital","description":"Re7 Labs is the on-chain risk curation and vault management arm of Re7 Capital, a London-based DeFi hedge fund, and is one of the largest DeFi-native vault curators with capital deployed across protocols including Morpho, Mellow, Symbiotic, and Gearbox.","entityType":"Corporation","jurisdiction":"United Kingdom","foundedYear":2021},
  "0xdc47b44e97806e22166a5710e3a60f92c0c9e085": {"website":"https://mainstreet.finance","twitter":"MainSt_Finance","logoUrl":"https://unavatar.io/x/MainSt_Finance","description":"Mainstreet (Main St / MainStreet.Finance) is a DeFi stablecoin yield protocol built on Sonic that issues msUSD, a dollar-pegged yield-bearing stablecoin, and smsUSD, its staked counterpart, generating yield via delta-neutral options-arbitrage strategies."},
  "0x90d0f26025571295d18a6c041e47450b81886b51": {"website":"https://yearn.fi","twitter":"yearnfi","logoUrl":"https://unavatar.io/x/yearnfi","description":"Yearn Finance is a decentralized yield-aggregation protocol on Ethereum that automates capital allocation across DeFi strategies through its vaults.","entityType":"DAO","foundedYear":2020},
  "0xe5e2baf96198c56380ddd5e992d7d1ada0e989c0": {"website":"https://www.originprotocol.com","twitter":"OriginProtocol","logoUrl":"https://unavatar.io/x/OriginProtocol","description":"Origin Protocol is an Ethereum-based DeFi project that builds yield-bearing stablecoin and token products (OUSD, OETH) and operates Automated Redemption Manager (ARM) vaults, deploying collateral into onchain strategies on protocols such as Morpho and Curve.","entityType":"Corporation","jurisdiction":"United States","foundedYear":2017},
  "tc:tulipa-capital": {"website":"https://www.tulipa.capital/","twitter":"tulipacapital","logoUrl":"https://unavatar.io/x/tulipacapital","description":"Tulipa Capital is a boutique crypto-native investment and risk-curation firm that operates as a curator of DeFi lending vaults, including vaults on the Morpho protocol.","entityType":"Corporation","foundedYear":2020},
  "0xba75546acd56b3a9142f94f179b03970ee4283fd": {"website":"https://keyrock.com","twitter":"KeyrockTrading","logoUrl":"https://unavatar.io/x/KeyrockTrading","description":"Keyrock is a digital asset market maker and trading firm that operates as a curator of USDC vaults on Morpho, allocating liquidity across DeFi lending markets.","entityType":"Corporation","jurisdiction":"Belgium","foundedYear":2017},
  "tc:nunchi": {"website":"https://nunchi.trade","twitter":"nunchitrade","logoUrl":"https://unavatar.io/x/nunchitrade","description":"Nunchi is a decentralized \"Yield Exchange\" (YEX) building perpetuals markets on yield itself — letting users trade onchain yield rates, funding/borrow rates, LSTs, Pendle YTs and RWA credit with leverage — and integrates with Pendle for vault management and liquidity positions.","entityType":"Corporation","jurisdiction":"Saint Lucia","foundedYear":2025},
  "tc:theoriq": {"website":"https://www.theoriq.ai","twitter":"TheoriqAI","logoUrl":"https://unavatar.io/x/TheoriqAI","description":"Theoriq is an AI-agent infrastructure project (developed by ChainML Labs) that builds AI-curated DeFi vault products for onchain yield, including AlphaVault for ETH-native yield.","entityType":"Corporation","foundedYear":2022},
  "0xda6b209d7619567cfdae61dabbfbac1c8a08f2bc": {"website":"https://etherealm.one/","twitter":"myetherealm","logoUrl":"https://unavatar.io/x/myetherealm","description":"Etherealm (Etherealm Research) is an on-chain risk-engineering firm that curates DeFi lending vaults, including a USDC vault on Morpho built around a proprietary \"Morpho Vault Manager\" and a barbell risk strategy."},
  "0x46057881e0b9d190920fb823f840b837f65745d5": {"website":"https://www.alphanonce.com/","twitter":"SingularV__","logoUrl":"https://unavatar.io/x/SingularV__","description":"SingularV is an onchain strategy brand operated by the crypto hedge fund Alphanonce that curates Morpho lending vaults (e.g. SingularV ETH and SingularV USDC), committing its own proprietary capital and applying active risk management.","entityType":"Corporation","jurisdiction":"Singapore","foundedYear":2018},
  "tc:r2": {"website":"https://www.r2.money","twitter":"r2yield","logoUrl":"https://unavatar.io/x/r2yield","description":"R2 is an on-chain asset-management protocol that issues R2USD, a yield-bearing stablecoin backed by tokenized real-world assets (U.S. Treasuries, money market funds, and private credit), routing stablecoin capital to institutional-grade yield strategies via a vault-based architecture.","entityType":"Corporation","foundedYear":2025},
  "0xabac65decf3b770fedd2c6dd7841771bf2bbeb74": {"website":"https://detrade.fund/","twitter":"DeTradeFund","logoUrl":"https://unavatar.io/x/DeTradeFund","description":"DeTrade (DeTrade Fund) is a DeFi investment fund, active since 2020, that runs risk-managed yield strategies and curates on-chain vaults across major DeFi protocols for experienced investors, treasuries, and financial-service partners.","entityType":"Corporation","foundedYear":2020},
  "0xe2e9f4f2f1b6ffe50c2bedd6d2fda97e6698e9fe": {"name":"Bloom"},
  "0x2dcfaea213ff75ce9ccc36598d1c1180b6a37c08": {"website":"https://utorg.com","twitter":"utorg_official","logoUrl":"https://unavatar.io/x/utorg_official","description":"Utorg (UAB Utorg) is an EU-based, licensed fintech company providing crypto on/off-ramp infrastructure, stablecoin orchestration, and crypto-linked cards.","entityType":"Corporation","jurisdiction":"Lithuania"},
};
