/**
 * Server-side read of the loss-anchored Expected-Loss curator rating (from the
 * external risk engine, imported into CuratorRating by
 * scripts/import-risk-engine-ratings.ts). Read from precomputed DB — no client fetch.
 *
 * Coexists with the live 7-factor peer-percentile profile (curator-risk-profile.ts):
 * this is the durable headline grade; the percentile profile is the supporting detail.
 * Feature-flagged via NEXT_PUBLIC_FEATURE_RISK_GRADES.
 */
import { cache } from "react";
import { prisma } from "@/lib/db";

export const RISK_GRADES_ENABLED = process.env.NEXT_PUBLIC_FEATURE_RISK_GRADES === "true";

export interface CuratorEngineRating {
  grade: string; // A+ | A | B+ | B | C+ | C | D | E | NR
  elMedian: number;
  elCi: [number, number];
  pLossAnnual: number | null;
  lgdMedian: number | null;
  channels: { credit?: number; technical?: number; operational?: number };
  confidence: string; // Tight | Moderate | Wide
  flags: Record<string, boolean>;
  nVaults: number | null;
  tvlUsd: number | null;
  exposureMonths: number | null;
  events: number | null;
  methodologyVersion: string;
  schemaVersion: string;
  modelGit: string | null;
  generatedAt: string;
}

export interface VaultEngineRating {
  grade: string;
  elMedian: number;
  elCi: [number, number];
  pdAnnualMedian: number | null;
  lgdMedian: number | null;
}

/**
 * Per-vault loss-anchored grades for a set of vaults, keyed "<chainId>:<address>"
 * (the engine's vault key). Returns an empty map when the flag is off. One batched
 * query; render-time lookup is O(1).
 */
export const getVaultEngineRatings = cache(
  async (vaults: { chainId: number; address: string }[]): Promise<Record<string, VaultEngineRating>> => {
    if (!RISK_GRADES_ENABLED || vaults.length === 0) return {};
    const keys = vaults.map((v) => `${v.chainId}:${v.address.toLowerCase()}`);
    const rows = await prisma.vaultRating.findMany({ where: { vaultKey: { in: keys } } });
    const out: Record<string, VaultEngineRating> = {};
    for (const r of rows) {
      out[r.vaultKey] = {
        grade: r.grade,
        elMedian: r.elMedian,
        elCi: [r.elCiLow, r.elCiHigh],
        pdAnnualMedian: r.pdAnnualMedian,
        lgdMedian: r.lgdMedian,
      };
    }
    return out;
  },
);

export interface CuratorRatingRow {
  curatorAddress: string;
  name: string;
  grade: string;
  elMedian: number;
  elCi: [number, number];
  confidence: string;
  flags: Record<string, boolean>;
  nVaults: number | null;
  tvlUsd: number | null;
}

/** All curator ratings, safest-first, for the /ratings executive-summary table. */
export const getAllCuratorRatings = cache(async (): Promise<CuratorRatingRow[]> => {
  if (!RISK_GRADES_ENABLED) return [];
  const rows = await prisma.curatorRating.findMany({ orderBy: { elMedian: "asc" } });
  return rows.map((r) => ({
    curatorAddress: r.curatorAddress,
    name: r.name ?? r.curatorKey,
    grade: r.grade,
    elMedian: r.elMedian,
    elCi: [r.elCiLow, r.elCiHigh],
    confidence: r.confidence,
    flags: (r.flags as Record<string, boolean>) ?? {},
    nVaults: r.nVaults,
    tvlUsd: r.tvlUsd,
  }));
});

/** When the live ratings were generated by the offline engine (max over rows).
 *  Surfaced on /ratings so users see the grades are a pinned snapshot, not live. */
export const getRatingsGeneratedAt = cache(async (): Promise<string | null> => {
  if (!RISK_GRADES_ENABLED) return null;
  const row = await prisma.curatorRating.findFirst({
    orderBy: { generatedAt: "desc" },
    select: { generatedAt: true },
  });
  return row ? row.generatedAt.toISOString() : null;
});

/** Single-vault EL grade (for the vault detail page + deposit drawer). */
export const getVaultEngineRating = cache(
  async (chainId: number, address: string): Promise<VaultEngineRating | null> => {
    if (!RISK_GRADES_ENABLED) return null;
    const row = await prisma.vaultRating.findUnique({
      where: { vaultKey: `${chainId}:${address.toLowerCase()}` },
    });
    if (!row) return null;
    return {
      grade: row.grade,
      elMedian: row.elMedian,
      elCi: [row.elCiLow, row.elCiHigh],
      pdAnnualMedian: row.pdAnnualMedian,
      lgdMedian: row.lgdMedian,
    };
  },
);

export const getCuratorEngineRating = cache(
  async (curatorAddress: string): Promise<CuratorEngineRating | null> => {
    if (!RISK_GRADES_ENABLED) return null;
    const row = await prisma.curatorRating.findUnique({
      where: { curatorAddress: curatorAddress.toLowerCase() },
    });
    if (!row) return null;
    return {
      grade: row.grade,
      elMedian: row.elMedian,
      elCi: [row.elCiLow, row.elCiHigh],
      pLossAnnual: row.pLossAnnual,
      lgdMedian: row.lgdMedian,
      channels: (row.channels as CuratorEngineRating["channels"]) ?? {},
      confidence: row.confidence,
      flags: (row.flags as Record<string, boolean>) ?? {},
      nVaults: row.nVaults,
      tvlUsd: row.tvlUsd,
      exposureMonths: row.exposureMonths,
      events: row.events,
      methodologyVersion: row.methodologyVersion,
      schemaVersion: row.schemaVersion,
      modelGit: row.modelGit,
      generatedAt: row.generatedAt.toISOString(),
    };
  },
);
