/**
 * Extract likely curator name from vault name
 * Logic: Remove asset symbols and common vault keywords
 */
export function extractCuratorFromVaultName(vaultName: string): string {
  // Common asset symbols to remove
  const assetSymbols = [
    'USDC', 'USDT', 'DAI', 'WETH', 'ETH', 'WBTC', 'BTC',
    'PYUSD', 'EURC', 'LINK', 'sNUSD', 'cbBTC', 'wstETH',
    'AUSD', 'LUSD', 'FRAX', 'sUSD', 'TUSD', 'USDT0',
    'USDe', 'sUSDe', 'USDA', 'GHO', 'crvUSD', 'mkUSD',
    'eUSD', 'USD', 'USDP', 'GUSD', 'BUSD', 'RAI',
    'stETH', 'rETH', 'cbETH', 'swETH', 'osETH', 'mETH',
    'weETH', 'ezETH', 'rsETH', 'pufETH', 'eETH'
  ];

  // Common vault keywords to remove
  const vaultKeywords = [
    'Vault', 'V2', 'V1', 'V3', 'Main', 'Core', 'Prime', 'Frontier',
    'Blue', 'Balanced', 'Conservative', 'Aggressive', 'Yield',
    'High', 'Low', 'Instant', 'Reservoir', 'Premium', 'Enhanced',
    'OG', 'Normie', 'Serenity', 'Atlas', 'Anchor', 'RWA',
    'Flagship', 'Genesis', 'Alpha', 'Beta', 'Delta', 'Omega',
    'Max', 'Mini', 'Lite', 'Pro', 'Plus', 'Ultra',
    'Midcurve', 'Longcurve', 'Shortcurve'
  ];

  let name = vaultName;

  // Remove asset symbols (case insensitive, whole words)
  assetSymbols.forEach(symbol => {
    const regex = new RegExp(`\\b${symbol}\\b`, 'gi');
    name = name.replace(regex, '');
  });

  // Remove vault keywords (case insensitive, whole words)
  vaultKeywords.forEach(keyword => {
    const regex = new RegExp(`\\b${keyword}\\b`, 'gi');
    name = name.replace(regex, '');
  });

  // Clean up
  name = name
    .replace(/\s+/g, ' ')      // Multiple spaces → single space
    .replace(/[:\-–—]+/g, ' ') // Hyphens/colons/dashes → space
    .replace(/[()[\]{}]/g, '') // Remove brackets
    .trim();

  // If we extracted something reasonable (3-50 chars)
  if (name.length >= 2 && name.length <= 50) {
    // Capitalize first letter of each word
    return name
      .split(' ')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  // Fallback: return first 1-2 words of original name
  const words = vaultName.split(/\s+/);
  const fallback = words.slice(0, Math.min(2, words.length)).join(' ');
  return fallback;
}

/**
 * Check if a curator name looks auto-generated (needs extraction)
 */
export function isAutogeneratedCuratorName(name: string | null): boolean {
  if (!name) return true;

  // Matches patterns like "Curator 0x1234...abcd" or just addresses
  if (name.startsWith('Curator 0x')) return true;
  if (name.match(/^0x[a-fA-F0-9]{4,}$/)) return true;
  if (name === 'Unknown Curator') return true;

  return false;
}

// Test cases for verification
export const EXTRACTION_TEST_CASES: Record<string, string> = {
  'DeTrade Serenity USDC': 'DeTrade',
  'YieldNest RWA': 'YieldNest',
  'Stake DAO USDC v2': 'Stake DAO',
  'Gauntlet USDC Prime': 'Gauntlet',
  'Steakhouse Prime EURC': 'Steakhouse',
  'Re7 WETH': 'Re7',
  'Yearn OG USDC V2': 'Yearn',
  'Brrrstr USDC': 'Brrrstr',
  'Clearstar Yield USDC': 'Clearstar',
  'Hyperithm USDC Midcurve': 'Hyperithm',
  'Kabu USDC': 'Kabu',
  'Etherealm USDC': 'Etherealm',
  'Keyrock USDC': 'Keyrock',
  'Avantgarde WETH Conservative': 'Avantgarde',
  'Sentora USDC Main': 'Sentora',
  'Block Analitica WETH': 'Block Analitica',
  'MEV Capital wstETH': 'MEV Capital',
};

/**
 * Run tests to verify extraction logic
 */
export function runExtractionTests(): { passed: number; failed: number; results: string[] } {
  const results: string[] = [];
  let passed = 0;
  let failed = 0;

  for (const [input, expected] of Object.entries(EXTRACTION_TEST_CASES)) {
    const actual = extractCuratorFromVaultName(input);
    const match = actual.toLowerCase() === expected.toLowerCase();

    if (match) {
      passed++;
      results.push(`✓ "${input}" → "${actual}"`);
    } else {
      failed++;
      results.push(`✗ "${input}" → "${actual}" (expected: "${expected}")`);
    }
  }

  return { passed, failed, results };
}
