import { prisma } from "../lib/db";
import { morphoClient } from "../lib/graphql/client";
import {
  GET_VAULTS_V2_PAGINATED,
  GET_VAULTS_V1_PAGINATED,
  GET_MORPHO_CURATORS,
  GET_VAULT_V2_TRANSACTIONS,
  GET_VAULT_REALLOCATES,
  type VaultV2TransactionsResponse,
  type VaultReallocatesResponse,
} from "../lib/graphql/queries";
import { collectLiquidations } from "./collect-liquidations";
import { collectMarketAllocations } from "./collect-market-allocations";
import {
  v1ToCommonShape,
  type VaultV2sResponse,
  type VaultsV1Response,
  type MorphoVaultV2,
  type MorphoCanonicalCurator,
} from "../lib/types/vault";
import { calculateAllRiskMetrics } from "../lib/risk-calculator";
import { detectChanges, storeChanges } from "../lib/change-detector";
import {
  createCuratorSnapshots,
  detectCuratorAlerts,
  detectEcosystemAlerts,
  storePlatformAlerts,
  cleanupOldCuratorSnapshots,
} from "../lib/curator-alert-detector";
import { resolveCuratorAddress, resolveVaultCuratorAddress } from "../lib/curator-aliases";
import {
  extractCuratorFromVaultName,
  isAutogeneratedCuratorName,
} from "../lib/utils/extract-curator-name";
import { sanitizeApyForStorage } from "../lib/utils/sanitize-apy";
import { canonicalChainName } from "../lib/turtle/chain-mapper";

/**
 * Chains the Morpho pipeline ingests, both vault generations (V1 MetaMorpho +
 * V2). Ethereum keeps the original $1k floor (its vaults are long-tracked);
 * newly added chains use a $50k floor so dust vaults don't flood the directory
 * or the cron's 800s budget. The floor is enforced server-side in the GraphQL
 * where-clause and re-checked locally.
 */
export interface MorphoChainConfig {
  chainId: number;
  minTvlUsd: number;
}

export const MORPHO_CHAINS: MorphoChainConfig[] = [
  { chainId: 1, minTvlUsd: 1_000 }, // Ethereum
  { chainId: 8453, minTvlUsd: 50_000 }, // Base
  { chainId: 999, minTvlUsd: 50_000 }, // HyperEVM (Felix et al.)
  { chainId: 143, minTvlUsd: 50_000 }, // Monad
  { chainId: 747474, minTvlUsd: 50_000 }, // Katana
  { chainId: 42161, minTvlUsd: 50_000 }, // Arbitrum
  { chainId: 137, minTvlUsd: 50_000 }, // Polygon
  { chainId: 10, minTvlUsd: 50_000 }, // Optimism
  { chainId: 130, minTvlUsd: 50_000 }, // Unichain
];

const BATCH_SIZE = 100; // Vaults per API request
const PARALLEL_BATCH_SIZE = 3; // Vaults processed in parallel
const TRANSACTIONS_PER_VAULT = 50;
const MIN_TVL_USD = 1000; // Skip vaults below $1000 TVL
const API_DELAY_MS = 100; // Delay between API calls to respect rate limits

export interface CollectionResult {
  success: boolean;
  vaultsProcessed: number;
  vaultsSkipped: number;
  curatorsCreated: number;
  snapshotsCreated: number;
  transactionsCollected: number;
  reallocationsCollected: number;
  riskSnapshotsCreated: number;
  changesDetected: number;
  platformAlertsDetected: number;
  curatorSnapshotsCreated: number;
  errors: string[];
  // Source-level failures (a whole chain/generation failed to fetch, came back
  // empty while the DB tracks it, or every vault failed to process). Any entry
  // here means the run did NOT collect what it was asked to — the cron route
  // turns this into a non-200. Per-vault hiccups stay in `errors` only.
  sourceErrors: string[];
  duration: number;
}

export type MorphoGeneration = "v1" | "v2";

// A chain/generation that returns zero vaults while the DB still tracks more
// than this many active vaults for it is treated as a broken source, not an
// empty market.
const EMPTY_SOURCE_DB_THRESHOLD = 10;

export interface CollectionOptions {
  fetchAll?: boolean; // Fetch all vaults (default: true)
  skipTransactions?: boolean; // Skip transaction fetching for speed
  skipReallocations?: boolean; // Skip reallocation fetching for speed
  skipMarketAllocations?: boolean; // Skip market allocation collection
  skipLiquidations?: boolean; // Skip liquidation collection
  minTvlUsd?: number; // Minimum TVL to include
  verbose?: boolean; // Verbose logging
  // Restrict the run to these chains (cron lanes: Ethereum alone is ~2/3 of
  // the vault count and must finish within the function budget, so the other
  // chains run in their own invocation). Default: all MORPHO_CHAINS.
  chainIds?: number[];
  // Restrict the run to these vault generations (cron lanes: Ethereum V1 and
  // V2 each run in their own invocation). Default: both.
  generations?: MorphoGeneration[];
}

function log(message: string) {
  const timestamp = new Date().toISOString();
  console.log(`[${timestamp}] ${message}`);
}

function logError(message: string, error?: unknown) {
  const timestamp = new Date().toISOString();
  console.error(`[${timestamp}] ERROR: ${message}`, error ?? "");
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Fetch the canonical curator registry (org id/name + addresses across every
 * chain) once per run and index it by lowercase curator address. Used to
 * resolve a vault's curator address to the same Curator row regardless of
 * which chain the vault lives on. An empty map (registry fetch failure)
 * degrades gracefully to address-only resolution — today's behavior.
 */
export async function fetchMorphoCuratorRegistry(): Promise<Map<string, MorphoCanonicalCurator>> {
  const byAddress = new Map<string, MorphoCanonicalCurator>();
  let skip = 0;

  while (true) {
    try {
      const response = await morphoClient.request<{
        curators: { items: MorphoCanonicalCurator[] };
      }>(GET_MORPHO_CURATORS, { first: BATCH_SIZE, skip });

      const items = response.curators.items;
      for (const org of items) {
        for (const a of org.addresses) {
          const key = a.address.toLowerCase();
          if (!byAddress.has(key)) byAddress.set(key, org);
        }
      }
      if (items.length < BATCH_SIZE) break;
      skip += BATCH_SIZE;
      await sleep(API_DELAY_MS);
    } catch (error) {
      logError(`Failed to fetch curator registry at skip=${skip}`, error);
      break;
    }
  }

  log(`Curator registry: ${byAddress.size} curator addresses mapped`);
  return byAddress;
}

/**
 * Effective TVL floor for a chain: the per-chain floor, or the caller's
 * override when it is stricter. (The cron passes minTvlUsd=1000, which must
 * not lower the $50k floor on newly added chains.)
 */
function effectiveMinTvl(chain: MorphoChainConfig, options: CollectionOptions): number {
  return Math.max(chain.minTvlUsd, options.minTvlUsd ?? MIN_TVL_USD);
}

/**
 * Fetch all V2 vaults on one chain from the Morpho API with pagination.
 * Returns vaults sorted by TVL descending. A failure after the first page
 * returns the pages already fetched and records the failure in `pageErrors`
 * (the caller must surface it — a truncated list is not a clean run).
 */
export async function fetchAllVaults(
  chain: MorphoChainConfig,
  options: CollectionOptions = {},
  pageErrors: string[] = []
): Promise<MorphoVaultV2[]> {
  const allVaults: MorphoVaultV2[] = [];
  let skip = 0;
  let hasMore = true;
  const minTvl = effectiveMinTvl(chain, options);

  log(`Fetching V2 vaults for chain ${chain.chainId} (min TVL: $${minTvl.toLocaleString()})...`);

  while (hasMore) {
    try {
      const response = await morphoClient.request<VaultV2sResponse>(
        GET_VAULTS_V2_PAGINATED,
        {
          first: BATCH_SIZE,
          skip,
          chainId: chain.chainId,
          minTvl,
        }
      );

      const vaults = response.vaultV2s.items;

      if (vaults.length === 0) {
        hasMore = false;
      } else {
        // Filter by minimum TVL (backstop — the where-clause already applies it)
        // VaultV2.avgApy is no longer served: fall back to the (sanitized) spot
        // apy, which tracked avgApy within 0.04pp (median) over Aug 20-26 2026.
        // Keeps the vault-page APY, curator gross APY and APY alerts alive.
        const validVaults = vaults
          .filter((v) => (v.totalAssetsUsd ?? 0) >= minTvl)
          .map((v) => ({ ...v, avgApy: v.avgApy ?? sanitizeApyForStorage(v.apy) }));
        allVaults.push(...validVaults);

        if (options.verbose) {
          log(`  Fetched batch ${skip}-${skip + vaults.length}: ${validVaults.length}/${vaults.length} valid vaults`);
        }

        // If we got fewer vaults than batch size, or last vault is below min TVL, we're done
        if (vaults.length < BATCH_SIZE) {
          hasMore = false;
        } else {
          // Check if last vault is below minimum TVL (since sorted by TVL)
          const lastVault = vaults[vaults.length - 1];
          if ((lastVault.totalAssetsUsd ?? 0) < minTvl) {
            hasMore = false;
          } else {
            skip += BATCH_SIZE;
            // Small delay to respect rate limits
            await sleep(API_DELAY_MS);
          }
        }
      }
    } catch (error) {
      logError(`Failed to fetch vaults batch at skip=${skip} (chain ${chain.chainId})`, error);
      // First page failing means the query itself is broken (schema drift) or
      // the API is down — rethrow so the run fails loudly instead of quietly
      // collecting zero vaults (V2 was silently frozen Aug 26 -> Sep 30 this way).
      if (skip === 0) throw error;
      pageErrors.push(
        `V2 page at skip=${skip} failed (list truncated at ${allVaults.length}): ${error instanceof Error ? error.message : error}`
      );
      hasMore = false;
    }
  }

  log(`  Chain ${chain.chainId}: ${allVaults.length} V2 vaults`);
  return allVaults;
}

/**
 * Fetch all V1 (MetaMorpho) vaults on one chain, normalized to the common
 * shape. V1 vaults are separate contracts from V2 — both generations coexist.
 */
export async function fetchAllVaultsV1(
  chain: MorphoChainConfig,
  options: CollectionOptions = {},
  pageErrors: string[] = []
): Promise<MorphoVaultV2[]> {
  const allVaults: MorphoVaultV2[] = [];
  let skip = 0;
  let hasMore = true;
  const minTvl = effectiveMinTvl(chain, options);

  log(`Fetching V1 (MetaMorpho) vaults for chain ${chain.chainId} (min TVL: $${minTvl.toLocaleString()})...`);

  while (hasMore) {
    try {
      const response = await morphoClient.request<VaultsV1Response>(
        GET_VAULTS_V1_PAGINATED,
        {
          first: BATCH_SIZE,
          skip,
          chainId: chain.chainId,
          minTvl,
        }
      );

      const vaults = response.vaults.items;

      if (vaults.length === 0) {
        hasMore = false;
      } else {
        for (const v1 of vaults) {
          const common = v1ToCommonShape(v1);
          if (common && (common.totalAssetsUsd ?? 0) >= minTvl) {
            allVaults.push(common);
          }
        }

        if (vaults.length < BATCH_SIZE) {
          hasMore = false;
        } else {
          skip += BATCH_SIZE;
          await sleep(API_DELAY_MS);
        }
      }
    } catch (error) {
      logError(`Failed to fetch V1 vaults batch at skip=${skip} (chain ${chain.chainId})`, error);
      // First-page failure: fail loudly (see fetchAllVaults).
      if (skip === 0) throw error;
      pageErrors.push(
        `V1 page at skip=${skip} failed (list truncated at ${allVaults.length}): ${error instanceof Error ? error.message : error}`
      );
      hasMore = false;
    }
  }

  log(`  Chain ${chain.chainId}: ${allVaults.length} V1 vaults`);
  return allVaults;
}

/**
 * Validate vault data before processing.
 * Returns true if vault should be processed.
 */
function isValidVault(vault: MorphoVaultV2, minTvlUsd: number): { valid: boolean; reason?: string } {
  // Check minimum TVL
  if ((vault.totalAssetsUsd ?? 0) < minTvlUsd) {
    return { valid: false, reason: `TVL below $${minTvlUsd}` };
  }

  // Check for required fields
  if (!vault.address) {
    return { valid: false, reason: "Missing address" };
  }

  if (!vault.asset?.address) {
    return { valid: false, reason: "Missing asset info" };
  }

  return { valid: true };
}

async function fetchVaultTransactions(vaultAddress: string) {
  try {
    const response = await morphoClient.request<VaultV2TransactionsResponse>(
      GET_VAULT_V2_TRANSACTIONS,
      {
        vaultAddress,
        first: TRANSACTIONS_PER_VAULT,
      }
    );
    return response.vaultV2transactions.items;
  } catch (error) {
    logError(`Failed to fetch transactions for ${vaultAddress}`, error);
    return [];
  }
}

async function fetchVaultReallocations(vaultAddress: string) {
  try {
    const response = await morphoClient.request<VaultReallocatesResponse>(
      GET_VAULT_REALLOCATES,
      {
        vaultAddress,
        first: TRANSACTIONS_PER_VAULT,
      }
    );
    return response.vaultReallocates.items;
  } catch (error) {
    logError(`Failed to fetch reallocations for ${vaultAddress}`, error);
    return [];
  }
}

/**
 * Ensure curator exists in database. Creates new record if not found.
 *
 * Resolution order:
 *  1. Alias-normalized address lookup (existing behavior — keeps every
 *     Ethereum-era curator row stable).
 *  2. Canonical identity from the Morpho curator registry: the org's curator
 *     addresses across ALL chains. This is what stops "Gauntlet on Base" from
 *     minting a second Gauntlet row next to the Ethereum one.
 *  3. Create, preferring the registry's display name over the vault-name guess.
 *
 * Returns the curator ID.
 */
async function ensureCuratorExists(
  curatorAddress: string,
  vaultName?: string,
  canonical?: MorphoCanonicalCurator | null
): Promise<{ curatorId: string; created: boolean }> {
  const normalizedAddress = resolveCuratorAddress(curatorAddress);
  const canonicalName = canonical?.name?.trim() || null;

  // Try to find existing curator by direct (alias-resolved) address
  let curator = await prisma.curator.findUnique({
    where: { address: normalizedAddress },
  });

  // Fall back to the org's other known addresses (any chain)
  if (!curator && canonical && canonical.addresses.length > 0) {
    curator = await prisma.curator.findFirst({
      where: {
        address: {
          in: canonical.addresses.map((a) => a.address),
          mode: "insensitive",
        },
      },
    });
  }

  if (curator) {
    // If curator exists but has auto-generated name, try to update it
    if (isAutogeneratedCuratorName(curator.name)) {
      const betterName =
        canonicalName ?? (vaultName ? extractCuratorFromVaultName(vaultName) : null);
      if (betterName && betterName.length >= 2) {
        await prisma.curator.update({
          where: { id: curator.id },
          data: { name: betterName },
        });
        log(`  Updated curator name: ${betterName} (from: ${canonicalName ? "registry" : vaultName})`);
      }
    }
    return { curatorId: curator.id, created: false };
  }

  // Best available name: registry first, vault-name extraction second
  const extractedName =
    canonicalName ?? (vaultName ? extractCuratorFromVaultName(vaultName) : null);

  // Create new curator with extracted or default name
  try {
    curator = await prisma.curator.create({
      data: {
        address: normalizedAddress,
        name: extractedName || null,
      },
    });
    log(`  Created new curator: ${extractedName || normalizedAddress.slice(0, 10)}... (from: ${canonicalName ? "registry" : vaultName || 'no vault'})`);
    return { curatorId: curator.id, created: true };
  } catch {
    // May already exist due to race condition
    const existing = await prisma.curator.findUnique({
      where: { address: normalizedAddress },
    });
    return { curatorId: existing?.id ?? "", created: false };
  }
}

/** Per-chain, per-generation context threaded through vault processing. */
interface ChainContext {
  chainId: number;
  chainName: string;
  isV1: boolean; // V1 has no adapters/transactions endpoints — skip those steps
  curatorRegistry: Map<string, MorphoCanonicalCurator>;
}

async function upsertVault(
  vault: MorphoVaultV2,
  ctx: ChainContext
): Promise<{ vaultId: string; curatorCreated: boolean; skipped?: boolean }> {
  const existing = await prisma.vault.findUnique({
    where: { address: vault.address },
  });

  // Vault.address is globally unique (not per chain). A same-address vault on a
  // different chain would clobber the original row — skip it loudly instead.
  // Morpho factories don't reuse addresses across chains today, so this should
  // stay at zero; if it ever fires, address+chainId needs a composite key.
  if (existing && existing.chainId !== ctx.chainId) {
    log(`  ⚠ Address collision across chains, skipping: ${vault.address} (db chain ${existing.chainId}, api chain ${ctx.chainId})`);
    return { vaultId: existing.id, curatorCreated: false, skipped: true };
  }

  // Link to curator if available
  let curatorId: string | null = null;
  let curatorCreated = false;

  // Canonical org: inline on V1 vaults; V2 resolves via the per-run registry
  const canonical =
    vault.curators?.items?.[0] ??
    (vault.curator?.address
      ? ctx.curatorRegistry.get(vault.curator.address.toLowerCase()) ?? null
      : null);
  if (vault.curator?.address) {
    // Check for vault-level curator overrides (e.g. Clearstar vaults under Re7's address)
    const resolvedCuratorAddress = resolveVaultCuratorAddress(vault.address, vault.curator.address);
    const curatorResult = await ensureCuratorExists(resolvedCuratorAddress, vault.name, canonical);
    curatorId = curatorResult.curatorId;
    curatorCreated = curatorResult.created;
  } else if (canonical && canonical.addresses.length > 0) {
    // V1 vaults occasionally report no state.curator while the registry still
    // attributes them — use the org's first known address as the curator key.
    const curatorResult = await ensureCuratorExists(canonical.addresses[0].address, vault.name, canonical);
    curatorId = curatorResult.curatorId;
    curatorCreated = curatorResult.created;
  }

  if (existing) {
    await prisma.vault.update({
      where: { address: vault.address },
      data: {
        name: vault.name,
        symbol: vault.symbol,
        chainId: ctx.chainId,
        chainName: ctx.chainName,
        onchainAddress: vault.address.toLowerCase(),
        curatorAddress: vault.curator?.address,
        curatorId,
        performanceFee: vault.performanceFee,
        managementFee: vault.managementFee,
        warnings: JSON.parse(JSON.stringify(vault.warnings ?? [])),
        listed: vault.listed ?? true,
        creationTimestamp: vault.creationTimestamp ? parseInt(String(vault.creationTimestamp), 10) : undefined,
        pendingConfigs: JSON.parse(JSON.stringify(vault.pendingConfigs?.items ?? [])),
        updatedAt: new Date(),
      },
    });
    return { vaultId: existing.id, curatorCreated };
  } else {
    const created = await prisma.vault.create({
      data: {
        address: vault.address,
        name: vault.name,
        symbol: vault.symbol,
        chainId: ctx.chainId,
        chainName: ctx.chainName,
        onchainAddress: vault.address.toLowerCase(),
        assetAddress: vault.asset.address,
        assetSymbol: vault.asset.symbol,
        assetDecimals: vault.asset.decimals,
        curatorAddress: vault.curator?.address,
        curatorId,
        performanceFee: vault.performanceFee,
        managementFee: vault.managementFee,
        warnings: JSON.parse(JSON.stringify(vault.warnings ?? [])),
        listed: vault.listed ?? true,
        creationTimestamp: vault.creationTimestamp ? parseInt(String(vault.creationTimestamp), 10) : undefined,
        pendingConfigs: JSON.parse(JSON.stringify(vault.pendingConfigs?.items ?? [])),
      },
    });
    return { vaultId: created.id, curatorCreated };
  }
}

function calculateSharePrice(vault: MorphoVaultV2): number {
  if (vault.sharePrice) {
    return vault.sharePrice;
  }

  const totalAssets = BigInt(vault.totalAssets || "0");
  const totalSupply = BigInt(vault.totalSupply || "1");

  if (totalSupply === 0n) {
    return 1;
  }

  return Number(totalAssets) / Number(totalSupply);
}

async function createSnapshot(vaultId: string, vault: MorphoVaultV2) {
  const sharePrice = calculateSharePrice(vault);

  // Calculate liquidityUsd from liquidity (raw asset units) and price
  let liquidityUsd: number | null = null;
  if (vault.liquidity && vault.totalAssets && vault.totalAssetsUsd) {
    const totalAssets = BigInt(vault.totalAssets);
    const liquidity = BigInt(vault.liquidity);
    if (totalAssets > 0n) {
      // Calculate price per unit: totalAssetsUsd / totalAssets
      // Then: liquidityUsd = liquidity * (totalAssetsUsd / totalAssets)
      liquidityUsd = Number(liquidity) * (vault.totalAssetsUsd / Number(totalAssets));
    }
  }

  // Sanity check: reject absurd APY values from the Morpho API. avgApy may be
  // undefined (VaultV2.avgApy is no longer served) — normalize so it isn't
  // logged as "bad".
  const rawAvgApy = vault.avgApy ?? null;
  const sanitizedAvgApy = sanitizeApyForStorage(rawAvgApy);
  const sanitizedAvgNetApy = sanitizeApyForStorage(vault.avgNetApy);

  if (sanitizedAvgApy !== rawAvgApy || sanitizedAvgNetApy !== vault.avgNetApy) {
    log(`  ⚠ Rejected bad APY for ${vaultId}: avgApy=${vault.avgApy}, avgNetApy=${vault.avgNetApy}`);
  }

  await prisma.vaultSnapshot.create({
    data: {
      vaultId,
      totalAssets: String(vault.totalAssets),
      totalAssetsUsd: vault.totalAssetsUsd ?? 0,
      totalSupply: String(vault.totalSupply),
      sharePrice,
      liquidity: vault.liquidity ? String(vault.liquidity) : null,
      liquidityUsd,
      apy: vault.apy,
      netApy: vault.netApy,
      avgApy: sanitizedAvgApy,
      avgNetApy: sanitizedAvgNetApy,
    },
  });
}

async function storeAdapterAllocations(
  vaultId: string,
  vault: MorphoVaultV2,
  snapshotTime: Date
) {
  const totalAssetsUsd = vault.totalAssetsUsd || 0;

  const allocations = vault.adapters.items.map((adapter) => ({
    vaultId,
    adapterAddress: adapter.address,
    adapterType: adapter.type,
    assets: String(adapter.assets),
    assetsUsd: adapter.assetsUsd ?? 0,
    allocationPct:
      totalAssetsUsd > 0 ? (adapter.assetsUsd / totalAssetsUsd) * 100 : 0,
    snapshotTime,
  }));

  if (allocations.length > 0) {
    await prisma.adapterAllocation.createMany({
      data: allocations,
    });
  }

  return allocations;
}

/**
 * Calculate USD value for a transaction based on shares and vault data.
 *
 * Key insight: ERC4626 vaults use 18 decimals for shares, but the underlying
 * asset may have different decimals (e.g., 6 for USDC).
 *
 * Formula:
 * - sharesHuman = shares / 10^18 (shares always have 18 decimals)
 * - assetsHuman = sharesHuman * sharePrice (sharePrice converts shares to assets)
 * - assetPriceUsd = totalAssetsUsd / (totalAssets / 10^assetDecimals)
 * - assetsUsd = assetsHuman * assetPriceUsd
 */
const SHARE_DECIMALS = 18; // ERC4626 standard

function calculateTransactionUsdValue(
  shares: string | null,
  sharePrice: number,
  totalAssets: string,
  totalAssetsUsd: number,
  assetDecimals: number
): { assets: string | null; assetsUsd: number | null } {
  if (!shares || !sharePrice || !totalAssets || !totalAssetsUsd) {
    return { assets: null, assetsUsd: null };
  }

  try {
    const sharesNum = parseFloat(shares);
    const totalAssetsNum = parseFloat(totalAssets);

    if (sharesNum === 0 || totalAssetsNum === 0) {
      return { assets: null, assetsUsd: null };
    }

    // Convert shares from raw to human-readable (18 decimals)
    const shareDivisor = Math.pow(10, SHARE_DECIMALS);
    const sharesHuman = sharesNum / shareDivisor;

    // Convert shares to assets using sharePrice
    // sharePrice = totalAssets(human) / totalSupply(human)
    const assetsHuman = sharesHuman * sharePrice;

    // Calculate asset price per token in USD
    const assetDivisor = Math.pow(10, assetDecimals);
    const totalAssetsHuman = totalAssetsNum / assetDivisor;
    const assetPriceUsd = totalAssetsUsd / totalAssetsHuman;

    // Calculate USD value
    const assetsUsd = assetsHuman * assetPriceUsd;

    // Store assets in raw units (with asset decimals)
    const assetsRaw = assetsHuman * assetDivisor;

    return {
      assets: assetsRaw.toString(),
      assetsUsd: Math.abs(assetsUsd), // Use absolute value since withdrawals show negative
    };
  } catch {
    return { assets: null, assetsUsd: null };
  }
}

interface VaultPriceData {
  sharePrice: number;
  totalAssets: string;
  totalAssetsUsd: number;
  assetDecimals: number;
}

async function storeTransactions(
  vaultId: string,
  transactions: Awaited<ReturnType<typeof fetchVaultTransactions>>,
  vaultPriceData: VaultPriceData
): Promise<number> {
  let stored = 0;

  for (const tx of transactions) {
    try {
      // Calculate USD value from shares
      const { assets, assetsUsd } = calculateTransactionUsdValue(
        tx.shares,
        vaultPriceData.sharePrice,
        vaultPriceData.totalAssets,
        vaultPriceData.totalAssetsUsd,
        vaultPriceData.assetDecimals
      );

      await prisma.vaultTransaction.upsert({
        where: {
          vaultId_txHash: {
            vaultId,
            txHash: tx.txHash,
          },
        },
        update: {
          // Update USD values for existing transactions
          assets,
          assetsUsd,
        },
        create: {
          vaultId,
          txHash: tx.txHash,
          blockNumber: tx.blockNumber,
          timestamp: new Date(Number(tx.timestamp) * 1000),
          type: tx.type,
          shares: tx.shares != null ? String(tx.shares) : null,
          assets,
          assetsUsd,
        },
      });
      stored++;
    } catch {
      // Skip duplicates silently
    }
  }

  return stored;
}

async function storeReallocations(
  vaultId: string,
  reallocations: Awaited<ReturnType<typeof fetchVaultReallocations>>
): Promise<number> {
  let stored = 0;

  for (const realloc of reallocations) {
    try {
      await prisma.vaultReallocation.create({
        data: {
          vaultId,
          timestamp: new Date(Number(realloc.timestamp) * 1000),
          txHash: realloc.hash,
          type: realloc.type,
          marketId: realloc.market?.marketId,
          amount: realloc.assets,
        },
      });
      stored++;
    } catch {
      // Skip duplicates or errors silently
    }
  }

  return stored;
}

/**
 * Recompute Curator.vaultCount / totalAssetsManaged in ONE set-based statement.
 *
 * Semantics are unchanged from the old per-curator loop: every vault linked to
 * the curator counts (no active/listed filter), TVL is the sum of each vault's
 * latest snapshot (vaults with no snapshot add 0), and curators with no vaults
 * are left untouched. The loop did ~1,500 sequential round trips (~8 min at
 * connection_limit=1) and pushed the core lane past its 900s cap; this runs in
 * tens of milliseconds. Latest-snapshot lookup is a LATERAL LIMIT 1 on the
 * (vaultId, timestamp) index — a DISTINCT ON over the whole snapshot table
 * measured ~6s on prod vs ~22ms for this form.
 */
async function updateCuratorStats() {
  log("Updating curator statistics...");

  const updated = await prisma.$executeRaw`
    UPDATE "Curator" c
    SET "vaultCount" = agg.vault_count,
        "totalAssetsManaged" = agg.total_assets,
        "updatedAt" = NOW()
    FROM (
      SELECT v."curatorId",
             COUNT(*)::int AS vault_count,
             COALESCE(SUM(latest."totalAssetsUsd"), 0) AS total_assets
      FROM "Vault" v
      LEFT JOIN LATERAL (
        SELECT s."totalAssetsUsd"
        FROM "VaultSnapshot" s
        WHERE s."vaultId" = v.id
        ORDER BY s."timestamp" DESC
        LIMIT 1
      ) latest ON true
      WHERE v."curatorId" IS NOT NULL
      GROUP BY v."curatorId"
    ) agg
    WHERE c.id = agg."curatorId"
  `;

  log(`  Curator stats updated: ${updated} curators`);
}

async function createRiskSnapshot(
  vaultId: string,
  vault: MorphoVaultV2,
  allocations: Array<{
    adapterAddress: string;
    adapterType: string;
    assets: string;
    assetsUsd: number;
    allocationPct: number;
  }>
) {
  const totalAssetsUsd = vault.totalAssetsUsd || 0;
  const totalAssets = BigInt(vault.totalAssets || "0");

  // Calculate idle assets
  const allocatedAssets = allocations.reduce(
    (sum, a) => sum + BigInt(a.assets),
    0n
  );
  const idleAssets = totalAssets - allocatedAssets;
  const idleAssetsPercent =
    totalAssets > 0n ? (Number(idleAssets) / Number(totalAssets)) * 100 : 0;

  // Calculate risk metrics
  const riskMetrics = calculateAllRiskMetrics(
    allocations.map((a) => ({
      address: a.adapterAddress,
      type: a.adapterType,
      assets: a.assets,
      assetsUsd: a.assetsUsd,
      allocationPct: a.allocationPct,
    })),
    idleAssetsPercent,
    totalAssetsUsd
  );

  await prisma.vaultRiskSnapshot.create({
    data: {
      vaultId,
      topAdapterPercent: riskMetrics.topAdapterPercent,
      top3AdaptersPercent: riskMetrics.top3AdaptersPercent,
      herfindahlIndex: riskMetrics.herfindahlIndex,
      numActiveAdapters: riskMetrics.numActiveAdapters,
      idleAssetsPercent: riskMetrics.idleAssetsPercent,
      hasLiquidityAdapter: riskMetrics.hasLiquidityAdapter,
      avgAllocationPercent: riskMetrics.avgAllocationPercent,
      largestAllocation: riskMetrics.largestAllocation,
      concentrationScore: riskMetrics.concentrationScore,
      liquidityScore: riskMetrics.liquidityScore,
      diversificationScore: riskMetrics.diversificationScore,
    },
  });
}

/**
 * Process a single vault - upsert, snapshot, transactions, risk metrics.
 */
async function processVault(
  vault: MorphoVaultV2,
  snapshotTime: Date,
  options: CollectionOptions,
  ctx: ChainContext
): Promise<{
  success: boolean;
  curatorCreated: boolean;
  txCount: number;
  reallocCount: number;
  changesDetected: number;
  error?: string;
}> {
  try {
    // Upsert vault record
    const { vaultId, curatorCreated, skipped } = await upsertVault(vault, ctx);
    if (skipped) {
      return { success: true, curatorCreated: false, txCount: 0, reallocCount: 0, changesDetected: 0 };
    }

    // Create snapshot
    await createSnapshot(vaultId, vault);

    // Store adapter allocations (V1 has no adapters — allocation is market-level)
    const allocations = ctx.isV1
      ? []
      : await storeAdapterAllocations(vaultId, vault, snapshotTime);

    // Fetch and store transactions (unless skipped; V2-only endpoint)
    let txCount = 0;
    if (!options.skipTransactions && !ctx.isV1) {
      const transactions = await fetchVaultTransactions(vault.address);
      const vaultPriceData: VaultPriceData = {
        sharePrice: vault.sharePrice || calculateSharePrice(vault),
        totalAssets: String(vault.totalAssets),
        totalAssetsUsd: vault.totalAssetsUsd || 0,
        assetDecimals: vault.asset.decimals,
      };
      txCount = await storeTransactions(vaultId, transactions, vaultPriceData);
    }

    // Fetch and store reallocations (unless skipped; V2-only endpoint)
    let reallocCount = 0;
    if (!options.skipReallocations && !ctx.isV1) {
      const reallocations = await fetchVaultReallocations(vault.address);
      reallocCount = await storeReallocations(vaultId, reallocations);
    }

    // Create risk snapshot. Skipped for V1: with no adapter data every metric
    // would read "100% idle / zero diversification", which is a data artifact,
    // not a risk signal.
    if (!ctx.isV1) {
      await createRiskSnapshot(vaultId, vault, allocations);
    }

    // Detect and store changes
    let changesDetected = 0;
    try {
      const currentSnapshot = {
        totalAssets: String(vault.totalAssets),
        totalAssetsUsd: vault.totalAssetsUsd || 0,
        sharePrice: vault.sharePrice || 1,
        avgApy: vault.avgApy || null,
        timestamp: snapshotTime,
      };

      const vaultData = {
        id: vaultId,
        name: vault.name,
        symbol: vault.symbol,
        assetSymbol: vault.asset.symbol,
        assetDecimals: vault.asset.decimals,
        curatorAddress: vault.curator?.address ?? "",
      };

      const changes = await detectChanges(vaultData, currentSnapshot);
      if (changes.length > 0) {
        changesDetected = await storeChanges(changes);
      }
    } catch {
      // Changes detection is non-critical, continue
    }

    return { success: true, curatorCreated, txCount, reallocCount, changesDetected };
  } catch (error) {
    return {
      success: false,
      curatorCreated: false,
      txCount: 0,
      reallocCount: 0,
      changesDetected: 0,
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

/**
 * Process vaults in parallel batches for efficiency.
 */
async function processVaultsBatch(
  vaults: MorphoVaultV2[],
  snapshotTime: Date,
  options: CollectionOptions,
  ctx: ChainContext
): Promise<{
  processed: number;
  curatorsCreated: number;
  txCollected: number;
  reallocsCollected: number;
  changesDetected: number;
  errors: string[];
}> {
  let processed = 0;
  let curatorsCreated = 0;
  let txCollected = 0;
  let reallocsCollected = 0;
  let changesDetected = 0;
  const errors: string[] = [];

  for (let i = 0; i < vaults.length; i += PARALLEL_BATCH_SIZE) {
    const batch = vaults.slice(i, i + PARALLEL_BATCH_SIZE);

    const results = await Promise.all(
      batch.map((vault) => processVault(vault, snapshotTime, options, ctx))
    );

    for (let j = 0; j < results.length; j++) {
      const result = results[j];
      const vault = batch[j];

      if (result.success) {
        processed++;
        if (result.curatorCreated) curatorsCreated++;
        txCollected += result.txCount;
        reallocsCollected += result.reallocCount;
        changesDetected += result.changesDetected;
      } else {
        errors.push(`${vault.name}: ${result.error}`);
      }
    }

    if (options.verbose) {
      log(`  Processed ${Math.min(i + PARALLEL_BATCH_SIZE, vaults.length)}/${vaults.length} vaults`);
    }

    // Small delay between batches
    if (i + PARALLEL_BATCH_SIZE < vaults.length) {
      await sleep(API_DELAY_MS);
    }
  }

  return { processed, curatorsCreated, txCollected, reallocsCollected, changesDetected, errors };
}

/**
 * Main data collection function.
 * Fetches all vaults from Morpho API and stores snapshots, transactions, and risk data.
 */
/**
 * Active Morpho vaults the DB tracks for one chain + generation. Vault has no
 * generation column; V2 is told apart by its risk snapshots (only V2 vaults get
 * them — see processVault). Only called when a source comes back empty.
 */
async function countTrackedVaults(chainId: number, isV1: boolean): Promise<number> {
  return prisma.vault.count({
    where: {
      dataSource: "morpho",
      active: true,
      chainId,
      riskSnapshots: isV1 ? { none: {} } : { some: {} },
    },
  });
}

export async function collectData(options: CollectionOptions = {}): Promise<CollectionResult> {
  const startTime = Date.now();
  const errors: string[] = [];
  const sourceErrors: string[] = [];
  const minTvlUsd = options.minTvlUsd ?? MIN_TVL_USD;

  log("=".repeat(60));
  log("Starting data collection...");
  log(`Options: fetchAll=${options.fetchAll ?? true}, minTvl=$${minTvlUsd}, skipTx=${options.skipTransactions ?? false}`);

  try {
    const snapshotTime = new Date();

    // Aggregate across chains and vault generations
    let totalValid = 0;
    let skippedCount = 0;
    const result = {
      processed: 0,
      curatorsCreated: 0,
      txCollected: 0,
      reallocsCollected: 0,
      changesDetected: 0,
    };

    // Canonical curator identities, fetched once and shared by every chain
    const curatorRegistry = await fetchMorphoCuratorRegistry();

    // Each chain is fetched and processed independently: one chain's API
    // trouble must not take down the whole collection run.
    const chains = options.chainIds
      ? MORPHO_CHAINS.filter((c) => options.chainIds!.includes(c.chainId))
      : MORPHO_CHAINS;
    for (const chain of chains) {
      const chainName = canonicalChainName(chain.chainId);
      const chainMinTvl = effectiveMinTvl(chain, options);

      const generations = options.generations ?? ["v2", "v1"];
      for (const isV1 of [false, true]) {
        if (!generations.includes(isV1 ? "v1" : "v2")) continue;
        const ctx: ChainContext = { chainId: chain.chainId, chainName, isV1, curatorRegistry };
        const label = `${chainName} ${isV1 ? "V1" : "V2"}`;

        try {
          const pageErrors: string[] = [];
          const fetched = isV1
            ? await fetchAllVaultsV1(chain, options, pageErrors)
            : await fetchAllVaults(chain, options, pageErrors);
          // A later page failed: process what was fetched, but the run is not
          // clean — the tail of the list keeps its old snapshot.
          for (const e of pageErrors) {
            const msg = `${label}: ${e}`;
            logError(msg);
            errors.push(msg);
            sourceErrors.push(msg);
          }

          // Validate and filter vaults
          const validVaults: MorphoVaultV2[] = [];
          for (const vault of fetched) {
            const validation = isValidVault(vault, chainMinTvl);
            if (validation.valid) {
              validVaults.push(vault);
            } else {
              skippedCount++;
              if (options.verbose) {
                log(`  Skipped ${vault.name || vault.address}: ${validation.reason}`);
              }
            }
          }
          totalValid += validVaults.length;

          if (validVaults.length === 0) {
            // An empty answer for a chain we track is a broken source (e.g. a
            // query that "succeeds" with nothing), not an empty market.
            const tracked = await countTrackedVaults(chain.chainId, isV1);
            if (tracked > EMPTY_SOURCE_DB_THRESHOLD) {
              const msg = `${label}: API returned 0 vaults but DB tracks ${tracked} active`;
              logError(msg);
              errors.push(msg);
              sourceErrors.push(msg);
            }
            continue;
          }
          log(`Processing ${validVaults.length} ${label} vaults...`);

          const batchResult = await processVaultsBatch(validVaults, snapshotTime, options, ctx);
          errors.push(...batchResult.errors);
          if (batchResult.processed === 0) {
            sourceErrors.push(`${label}: all ${validVaults.length} vaults failed processing`);
          }
          result.processed += batchResult.processed;
          result.curatorsCreated += batchResult.curatorsCreated;
          result.txCollected += batchResult.txCollected;
          result.reallocsCollected += batchResult.reallocsCollected;
          result.changesDetected += batchResult.changesDetected;
        } catch (error) {
          const msg = `${label} collection failed: ${error instanceof Error ? error.message : error}`;
          logError(msg);
          errors.push(msg);
          sourceErrors.push(msg);
        }
      }
    }

    log(`Processed: ${result.processed}/${totalValid} vaults across ${chains.length} chain(s)`);

    // Update curator statistics
    await updateCuratorStats();

    // Curator & ecosystem-level alert detection
    let platformAlertsDetected = 0;
    let curatorSnapshotsCreated = 0;
    try {
      // 1. Create curator snapshots (for AUM history)
      curatorSnapshotsCreated = await createCuratorSnapshots();
      log(`  Curator snapshots created: ${curatorSnapshotsCreated}`);

      // 2. Detect curator-level alerts
      const curatorAlerts = await detectCuratorAlerts();
      if (curatorAlerts.length > 0) {
        const stored = await storePlatformAlerts(curatorAlerts);
        platformAlertsDetected += stored;
        log(`  Curator alerts: ${stored} stored (${curatorAlerts.length} detected)`);
      }

      // 3. Detect ecosystem-level alerts
      const ecosystemAlerts = await detectEcosystemAlerts();
      if (ecosystemAlerts.length > 0) {
        const stored = await storePlatformAlerts(ecosystemAlerts);
        platformAlertsDetected += stored;
        log(`  Ecosystem alerts: ${stored} stored (${ecosystemAlerts.length} detected)`);
      }

      // 4. Cleanup old snapshots (cheap operation)
      const cleaned = await cleanupOldCuratorSnapshots();
      if (cleaned > 0) {
        log(`  Cleaned up ${cleaned} old curator snapshots`);
      }
    } catch (error) {
      logError("Failed to run curator/ecosystem alert detection (non-critical)", error);
    }

    // Collect market allocations (needed for liquidation join)
    if (!options.skipMarketAllocations) {
      log("Collecting market allocations...");
      try {
        const maResult = await collectMarketAllocations();
        log(`  Market allocations: ${maResult.allocationsStored} stored from ${maResult.vaultsProcessed} vaults`);
      } catch (error) {
        logError("Failed to collect market allocations (non-critical)", error);
      }
    }

    // Collect liquidation data
    if (!options.skipLiquidations) {
      log("Collecting liquidation data...");
      try {
        const liqResult = await collectLiquidations();
        log(`  Liquidations: ${liqResult.stored} new, ${liqResult.fetched} fetched`);
      } catch (error) {
        logError("Failed to collect liquidations (non-critical)", error);
      }
    }

    // Print summary
    const vaultCount = await prisma.vault.count();
    const curatorCount = await prisma.curator.count();
    const snapshotCount = await prisma.vaultSnapshot.count();
    const allocationCount = await prisma.adapterAllocation.count();
    const txCount = await prisma.vaultTransaction.count();
    const reallocCount = await prisma.vaultReallocation.count();
    const riskCount = await prisma.vaultRiskSnapshot.count();
    const changeCount = await prisma.vaultChange.count();
    const platformAlertCount = await prisma.platformAlert.count();
    const curatorSnapshotTotal = await prisma.curatorSnapshot.count();

    log("-".repeat(60));
    log("Data collection completed!");
    log(`  Vaults processed: ${result.processed}/${totalValid}`);
    log(`  Vaults skipped: ${skippedCount}`);
    log(`  Curators created: ${result.curatorsCreated}`);
    log(`  Transactions collected: ${result.txCollected}`);
    log(`  Reallocations collected: ${result.reallocsCollected}`);
    log(`  Changes detected: ${result.changesDetected}`);
    log(`  Platform alerts detected: ${platformAlertsDetected}`);
    log(`  Curator snapshots created: ${curatorSnapshotsCreated}`);
    log("-".repeat(60));
    log("Database totals:");
    log(`  Vaults: ${vaultCount}`);
    log(`  Curators: ${curatorCount}`);
    log(`  Snapshots: ${snapshotCount}`);
    log(`  Allocations: ${allocationCount}`);
    log(`  Transactions: ${txCount}`);
    log(`  Reallocations: ${reallocCount}`);
    log(`  Risk Snapshots: ${riskCount}`);
    log(`  Changes: ${changeCount}`);
    log(`  Platform Alerts: ${platformAlertCount}`);
    log(`  Curator Snapshots: ${curatorSnapshotTotal}`);

    if (errors.length > 0) {
      log(`  Errors: ${errors.length}`);
      errors.slice(0, 5).forEach((e) => log(`    - ${e}`));
      if (errors.length > 5) {
        log(`    ... and ${errors.length - 5} more`);
      }
    }

    const duration = Date.now() - startTime;
    log(`  Duration: ${(duration / 1000).toFixed(1)}s`);
    log("=".repeat(60));

    return {
      success: errors.length === 0,
      vaultsProcessed: result.processed,
      vaultsSkipped: skippedCount,
      curatorsCreated: result.curatorsCreated,
      snapshotsCreated: result.processed,
      transactionsCollected: result.txCollected,
      reallocationsCollected: result.reallocsCollected,
      riskSnapshotsCreated: result.processed,
      changesDetected: result.changesDetected,
      platformAlertsDetected,
      curatorSnapshotsCreated,
      errors,
      sourceErrors,
      duration,
    };
  } catch (error) {
    const errorMsg = `Critical error during collection: ${error}`;
    logError(errorMsg);
    errors.push(errorMsg);
    sourceErrors.push(errorMsg);

    return {
      success: false,
      vaultsProcessed: 0,
      vaultsSkipped: 0,
      curatorsCreated: 0,
      snapshotsCreated: 0,
      transactionsCollected: 0,
      reallocationsCollected: 0,
      riskSnapshotsCreated: 0,
      changesDetected: 0,
      platformAlertsDetected: 0,
      curatorSnapshotsCreated: 0,
      errors,
      sourceErrors,
      duration: Date.now() - startTime,
    };
  }
}

/**
 * CLI entry point - runs collection and exits.
 */
async function main() {
  // Parse command line arguments
  const args = process.argv.slice(2);
  const options: CollectionOptions = {
    fetchAll: true,
    skipTransactions: args.includes("--skip-tx"),
    skipReallocations: args.includes("--skip-realloc"),
    verbose: args.includes("--verbose") || args.includes("-v"),
  };

  // Parse --min-tvl=X argument
  const minTvlArg = args.find((a) => a.startsWith("--min-tvl="));
  if (minTvlArg) {
    options.minTvlUsd = parseInt(minTvlArg.split("=")[1], 10);
  }

  try {
    const result = await collectData(options);

    if (!result.success) {
      console.error("Collection completed with errors:", result.errors);
      process.exit(1);
    }

    process.exit(0);
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

// Only run main() if this file is executed directly
const isDirectRun = require.main === module;
if (isDirectRun) {
  main();
}
