import { Prisma } from "@prisma/client";
import { prisma } from "../lib/db";
import { morphoClient } from "../lib/graphql/client";
import {
  GET_VAULTS_V2_PAGINATED,
  GET_VAULTS_V1_PAGINATED,
  GET_MORPHO_CURATORS,
  GET_VAULT_V2_TRANSACTIONS,
  GET_VAULT_REALLOCATES,
  type VaultV2TransactionsResponse,
  type VaultReallocatesResponse,
} from "../lib/graphql/queries";
import { collectLiquidations } from "./collect-liquidations";
import { collectMarketAllocations } from "./collect-market-allocations";
import {
  v1ToCommonShape,
  type VaultV2sResponse,
  type VaultsV1Response,
  type MorphoVaultV2,
  type MorphoCanonicalCurator,
} from "../lib/types/vault";
import { calculateAllRiskMetrics } from "../lib/risk-calculator";
import { detectAlertsBatch, storeChanges } from "../lib/change-detector";
import {
  createCuratorSnapshots,
  detectCuratorAlerts,
  detectEcosystemAlerts,
  storePlatformAlerts,
  cleanupOldCuratorSnapshots,
} from "../lib/curator-alert-detector";
import { resolveCuratorAddress, resolveVaultCuratorAddress } from "../lib/curator-aliases";
import {
  extractCuratorFromVaultName,
  isAutogeneratedCuratorName,
} from "../lib/utils/extract-curator-name";
import { sanitizeApyForStorage } from "../lib/utils/sanitize-apy";
import { canonicalChainName } from "../lib/turtle/chain-mapper";
import { assessPhantom, type PhantomBaseline } from "../lib/data-quality/phantom";
import { fetchPhantomBaselines, finalizeCollection } from "../lib/data-quality/maintenance";

/**
 * Chains the Morpho pipeline ingests, both vault generations (V1 MetaMorpho +
 * V2). Ethereum keeps the original $1k floor (its vaults are long-tracked);
 * newly added chains use a $50k floor so dust vaults don't flood the directory
 * or the cron's 800s budget. The floor is enforced server-side in the GraphQL
 * where-clause and re-checked locally.
 */
export interface MorphoChainConfig {
  chainId: number;
  minTvlUsd: number;
}

export const MORPHO_CHAINS: MorphoChainConfig[] = [
  { chainId: 1, minTvlUsd: 1_000 }, // Ethereum
  { chainId: 8453, minTvlUsd: 50_000 }, // Base
  { chainId: 999, minTvlUsd: 50_000 }, // HyperEVM (Felix et al.)
  { chainId: 143, minTvlUsd: 50_000 }, // Monad
  { chainId: 747474, minTvlUsd: 50_000 }, // Katana
  { chainId: 42161, minTvlUsd: 50_000 }, // Arbitrum
  { chainId: 137, minTvlUsd: 50_000 }, // Polygon
  { chainId: 10, minTvlUsd: 50_000 }, // Optimism
  { chainId: 130, minTvlUsd: 50_000 }, // Unichain
];

const BATCH_SIZE = 100; // Vaults per API request
// Vaults written per chunk: each write step is one statement per chunk, not
// one per vault (per-vault round trips cost ~4s/vault on the pooler).
const CHUNK_SIZE = 50;
const ROWS_PER_STATEMENT = 500; // Cap on rows in one INSERT / UPDATE ... VALUES
const API_CONCURRENCY = 4; // Per-vault transaction/reallocation fetches in flight
const TRANSACTIONS_PER_VAULT = 50;
const MIN_TVL_USD = 1000; // Skip vaults below $1000 TVL
const API_DELAY_MS = 100; // Delay between API calls to respect rate limits

export interface CollectionResult {
  success: boolean;
  vaultsProcessed: number;
  vaultsSkipped: number;
  curatorsCreated: number;
  snapshotsCreated: number;
  transactionsCollected: number;
  reallocationsCollected: number;
  riskSnapshotsCreated: number;
  changesDetected: number;
  platformAlertsDetected: number;
  curatorSnapshotsCreated: number;
  // Vaults whose snapshot this run flagged as phantom accrual (not counted).
  phantomFlagged: number;
  errors: string[];
  // Source-level failures (a whole chain/generation failed to fetch, came back
  // empty while the DB tracks it, or every vault failed to process). Any entry
  // here means the run did NOT collect what it was asked to — the cron route
  // turns this into a non-200. Per-vault hiccups stay in `errors` only.
  sourceErrors: string[];
  duration: number;
}

export type MorphoGeneration = "v1" | "v2";

// A chain/generation that returns zero vaults while the DB still tracks more
// than this many active vaults for it is treated as a broken source, not an
// empty market.
const EMPTY_SOURCE_DB_THRESHOLD = 10;

export interface CollectionOptions {
  fetchAll?: boolean; // Fetch all vaults (default: true)
  skipTransactions?: boolean; // Skip transaction fetching for speed
  skipReallocations?: boolean; // Skip reallocation fetching for speed
  skipMarketAllocations?: boolean; // Skip market allocation collection
  skipLiquidations?: boolean; // Skip liquidation collection
  minTvlUsd?: number; // Minimum TVL to include
  verbose?: boolean; // Verbose logging
  // Restrict the run to these chains (cron lanes: Ethereum alone is ~2/3 of
  // the vault count and must finish within the function budget, so the other
  // chains run in their own invocation). Default: all MORPHO_CHAINS.
  chainIds?: number[];
  // Restrict the run to these vault generations (cron lanes: Ethereum V1 and
  // V2 each run in their own invocation). Default: both.
  generations?: MorphoGeneration[];
  // Stop starting new vault chunks this long after the run began (the cron
  // keeps the rest of its function budget for the post-collection steps).
  // Deferred vaults are reported as a source error; they go first next run.
  // Default: no limit.
  timeBudgetMs?: number;
}

function log(message: string) {
  const timestamp = new Date().toISOString();
  console.log(`[${timestamp}] ${message}`);
}

function logError(message: string, error?: unknown) {
  const timestamp = new Date().toISOString();
  console.error(`[${timestamp}] ERROR: ${message}`, error ?? "");
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Fetch the canonical curator registry (org id/name + addresses across every
 * chain) once per run and index it by lowercase curator address. Used to
 * resolve a vault's curator address to the same Curator row regardless of
 * which chain the vault lives on. An empty map (registry fetch failure)
 * degrades gracefully to address-only resolution — today's behavior.
 */
export async function fetchMorphoCuratorRegistry(): Promise<Map<string, MorphoCanonicalCurator>> {
  const byAddress = new Map<string, MorphoCanonicalCurator>();
  let skip = 0;

  while (true) {
    try {
      const response = await morphoClient.request<{
        curators: { items: MorphoCanonicalCurator[] };
      }>(GET_MORPHO_CURATORS, { first: BATCH_SIZE, skip });

      const items = response.curators.items;
      for (const org of items) {
        for (const a of org.addresses) {
          const key = a.address.toLowerCase();
          if (!byAddress.has(key)) byAddress.set(key, org);
        }
      }
      if (items.length < BATCH_SIZE) break;
      skip += BATCH_SIZE;
      await sleep(API_DELAY_MS);
    } catch (error) {
      logError(`Failed to fetch curator registry at skip=${skip}`, error);
      break;
    }
  }

  log(`Curator registry: ${byAddress.size} curator addresses mapped`);
  return byAddress;
}

/**
 * Effective TVL floor for a chain: the per-chain floor, or the caller's
 * override when it is stricter. (The cron passes minTvlUsd=1000, which must
 * not lower the $50k floor on newly added chains.)
 */
function effectiveMinTvl(chain: MorphoChainConfig, options: CollectionOptions): number {
  return Math.max(chain.minTvlUsd, options.minTvlUsd ?? MIN_TVL_USD);
}

/**
 * Fetch all V2 vaults on one chain from the Morpho API with pagination.
 * Returns vaults sorted by TVL descending. A failure after the first page
 * returns the pages already fetched and records the failure in `pageErrors`
 * (the caller must surface it — a truncated list is not a clean run).
 */
export async function fetchAllVaults(
  chain: MorphoChainConfig,
  options: CollectionOptions = {},
  pageErrors: string[] = []
): Promise<MorphoVaultV2[]> {
  const allVaults: MorphoVaultV2[] = [];
  let skip = 0;
  let hasMore = true;
  const minTvl = effectiveMinTvl(chain, options);

  log(`Fetching V2 vaults for chain ${chain.chainId} (min TVL: $${minTvl.toLocaleString()})...`);

  while (hasMore) {
    try {
      const response = await morphoClient.request<VaultV2sResponse>(
        GET_VAULTS_V2_PAGINATED,
        {
          first: BATCH_SIZE,
          skip,
          chainId: chain.chainId,
          minTvl,
        }
      );

      const vaults = response.vaultV2s.items;

      if (vaults.length === 0) {
        hasMore = false;
      } else {
        // Filter by minimum TVL (backstop — the where-clause already applies it)
        // VaultV2.avgApy is no longer served: fall back to the (sanitized) spot
        // apy, which tracked avgApy within 0.04pp (median) over Aug 20-26 2026.
        // Keeps the vault-page APY, curator gross APY and APY alerts alive.
        const validVaults = vaults
          .filter((v) => (v.totalAssetsUsd ?? 0) >= minTvl)
          .map((v) => ({ ...v, avgApy: v.avgApy ?? sanitizeApyForStorage(v.apy) }));
        allVaults.push(...validVaults);

        if (options.verbose) {
          log(`  Fetched batch ${skip}-${skip + vaults.length}: ${validVaults.length}/${vaults.length} valid vaults`);
        }

        // If we got fewer vaults than batch size, or last vault is below min TVL, we're done
        if (vaults.length < BATCH_SIZE) {
          hasMore = false;
        } else {
          // Check if last vault is below minimum TVL (since sorted by TVL)
          const lastVault = vaults[vaults.length - 1];
          if ((lastVault.totalAssetsUsd ?? 0) < minTvl) {
            hasMore = false;
          } else {
            skip += BATCH_SIZE;
            // Small delay to respect rate limits
            await sleep(API_DELAY_MS);
          }
        }
      }
    } catch (error) {
      logError(`Failed to fetch vaults batch at skip=${skip} (chain ${chain.chainId})`, error);
      // First page failing means the query itself is broken (schema drift) or
      // the API is down — rethrow so the run fails loudly instead of quietly
      // collecting zero vaults (V2 was silently frozen Aug 26 -> Sep 30 this way).
      if (skip === 0) throw error;
      pageErrors.push(
        `V2 page at skip=${skip} failed (list truncated at ${allVaults.length}): ${error instanceof Error ? error.message : error}`
      );
      hasMore = false;
    }
  }

  log(`  Chain ${chain.chainId}: ${allVaults.length} V2 vaults`);
  return allVaults;
}

/**
 * Fetch all V1 (MetaMorpho) vaults on one chain, normalized to the common
 * shape. V1 vaults are separate contracts from V2 — both generations coexist.
 */
export async function fetchAllVaultsV1(
  chain: MorphoChainConfig,
  options: CollectionOptions = {},
  pageErrors: string[] = []
): Promise<MorphoVaultV2[]> {
  const allVaults: MorphoVaultV2[] = [];
  let skip = 0;
  let hasMore = true;
  const minTvl = effectiveMinTvl(chain, options);

  log(`Fetching V1 (MetaMorpho) vaults for chain ${chain.chainId} (min TVL: $${minTvl.toLocaleString()})...`);

  while (hasMore) {
    try {
      const response = await morphoClient.request<VaultsV1Response>(
        GET_VAULTS_V1_PAGINATED,
        {
          first: BATCH_SIZE,
          skip,
          chainId: chain.chainId,
          minTvl,
        }
      );

      const vaults = response.vaults.items;

      if (vaults.length === 0) {
        hasMore = false;
      } else {
        for (const v1 of vaults) {
          const common = v1ToCommonShape(v1);
          if (common && (common.totalAssetsUsd ?? 0) >= minTvl) {
            allVaults.push(common);
          }
        }

        if (vaults.length < BATCH_SIZE) {
          hasMore = false;
        } else {
          skip += BATCH_SIZE;
          await sleep(API_DELAY_MS);
        }
      }
    } catch (error) {
      logError(`Failed to fetch V1 vaults batch at skip=${skip} (chain ${chain.chainId})`, error);
      // First-page failure: fail loudly (see fetchAllVaults).
      if (skip === 0) throw error;
      pageErrors.push(
        `V1 page at skip=${skip} failed (list truncated at ${allVaults.length}): ${error instanceof Error ? error.message : error}`
      );
      hasMore = false;
    }
  }

  log(`  Chain ${chain.chainId}: ${allVaults.length} V1 vaults`);
  return allVaults;
}

/**
 * Validate vault data before processing.
 * Returns true if vault should be processed.
 */
function isValidVault(vault: MorphoVaultV2, minTvlUsd: number): { valid: boolean; reason?: string } {
  // Check minimum TVL
  if ((vault.totalAssetsUsd ?? 0) < minTvlUsd) {
    return { valid: false, reason: `TVL below $${minTvlUsd}` };
  }

  // Check for required fields
  if (!vault.address) {
    return { valid: false, reason: "Missing address" };
  }

  if (!vault.asset?.address) {
    return { valid: false, reason: "Missing asset info" };
  }

  return { valid: true };
}

async function fetchVaultTransactions(vaultAddress: string) {
  try {
    const response = await morphoClient.request<VaultV2TransactionsResponse>(
      GET_VAULT_V2_TRANSACTIONS,
      {
        vaultAddress,
        first: TRANSACTIONS_PER_VAULT,
      }
    );
    return response.vaultV2transactions.items;
  } catch (error) {
    logError(`Failed to fetch transactions for ${vaultAddress}`, error);
    return [];
  }
}

async function fetchVaultReallocations(vaultAddress: string) {
  try {
    const response = await morphoClient.request<VaultReallocatesResponse>(
      GET_VAULT_REALLOCATES,
      {
        vaultAddress,
        first: TRANSACTIONS_PER_VAULT,
      }
    );
    return response.vaultReallocates.items;
  } catch (error) {
    logError(`Failed to fetch reallocations for ${vaultAddress}`, error);
    return [];
  }
}

/** A Curator row as the run's in-memory cache holds it. */
interface CuratorRow {
  id: string;
  address: string;
  name: string | null;
}

/**
 * Every Curator row, read once per run (~200 rows) so resolving a vault's
 * curator costs no query. Creates and renames made by this run update it.
 */
interface CuratorCache {
  byAddress: Map<string, CuratorRow>; // exact address (findUnique semantics)
  byLowerAddress: Map<string, CuratorRow>; // case-insensitive match
}

function cacheCurator(cache: CuratorCache, row: CuratorRow) {
  cache.byAddress.set(row.address, row);
  const lower = row.address.toLowerCase();
  if (!cache.byLowerAddress.has(lower)) cache.byLowerAddress.set(lower, row);
}

async function loadCuratorCache(): Promise<CuratorCache> {
  const rows = await prisma.curator.findMany({ select: { id: true, address: true, name: true } });
  const cache: CuratorCache = { byAddress: new Map(), byLowerAddress: new Map() };
  for (const row of rows) cacheCurator(cache, row);
  return cache;
}

/**
 * Ensure curator exists in database. Creates new record if not found.
 *
 * Resolution order:
 *  1. Alias-normalized address lookup (existing behavior — keeps every
 *     Ethereum-era curator row stable).
 *  2. Canonical identity from the Morpho curator registry: the org's curator
 *     addresses across ALL chains. This is what stops "Gauntlet on Base" from
 *     minting a second Gauntlet row next to the Ethereum one.
 *  3. Create, preferring the registry's display name over the vault-name guess.
 *
 * Lookups read the run's curator cache; only a rename or a create writes.
 * Returns the curator ID.
 */
async function ensureCuratorExists(
  cache: CuratorCache,
  curatorAddress: string,
  vaultName?: string,
  canonical?: MorphoCanonicalCurator | null
): Promise<{ curatorId: string; created: boolean }> {
  const normalizedAddress = resolveCuratorAddress(curatorAddress);
  const canonicalName = canonical?.name?.trim() || null;

  // Try to find existing curator by direct (alias-resolved) address
  let curator = cache.byAddress.get(normalizedAddress) ?? null;

  // Fall back to the org's other known addresses (any chain, any case)
  if (!curator && canonical && canonical.addresses.length > 0) {
    for (const a of canonical.addresses) {
      curator = cache.byLowerAddress.get(a.address.toLowerCase()) ?? null;
      if (curator) break;
    }
  }

  if (curator) {
    // If curator exists but has auto-generated name, try to update it
    if (isAutogeneratedCuratorName(curator.name)) {
      const betterName =
        canonicalName ?? (vaultName ? extractCuratorFromVaultName(vaultName) : null);
      if (betterName && betterName.length >= 2) {
        await prisma.curator.update({
          where: { id: curator.id },
          data: { name: betterName },
        });
        curator.name = betterName;
        log(`  Updated curator name: ${betterName} (from: ${canonicalName ? "registry" : vaultName})`);
      }
    }
    return { curatorId: curator.id, created: false };
  }

  // Best available name: registry first, vault-name extraction second
  const extractedName =
    canonicalName ?? (vaultName ? extractCuratorFromVaultName(vaultName) : null);

  // Create new curator with extracted or default name
  try {
    const created = await prisma.curator.create({
      data: {
        address: normalizedAddress,
        name: extractedName || null,
      },
      select: { id: true, address: true, name: true },
    });
    cacheCurator(cache, created);
    log(`  Created new curator: ${extractedName || normalizedAddress.slice(0, 10)}... (from: ${canonicalName ? "registry" : vaultName || 'no vault'})`);
    return { curatorId: created.id, created: true };
  } catch {
    // May already exist due to race condition
    const existing = await prisma.curator.findUnique({
      where: { address: normalizedAddress },
      select: { id: true, address: true, name: true },
    });
    if (!existing) throw new Error(`Curator ${normalizedAddress} could not be created`);
    cacheCurator(cache, existing);
    return { curatorId: existing.id, created: false };
  }
}

/** Per-chain, per-generation context threaded through vault processing. */
interface ChainContext {
  chainId: number;
  chainName: string;
  isV1: boolean; // V1 has no adapters/transactions endpoints — skip those steps
  curatorRegistry: Map<string, MorphoCanonicalCurator>;
  // ~30-day-old snapshot per vault id, for the phantom-accrual test.
  phantomBaselines: Map<string, PhantomBaseline>;
  curators: CuratorCache;
}

/** The Vault columns the collector reads back: id, collision check, ordering. */
interface VaultRef {
  id: string;
  address: string;
  chainId: number;
  lastSnapshotAt: Date | null;
}
const VAULT_REF_SELECT = { id: true, address: true, chainId: true, lastSnapshotAt: true } as const;

/** Existing Vault rows for these addresses, keyed by address (one query). */
async function fetchVaultRefs(addresses: string[]): Promise<Map<string, VaultRef>> {
  const rows = await prisma.vault.findMany({
    where: { address: { in: addresses } },
    select: VAULT_REF_SELECT,
  });
  return new Map(rows.map((r) => [r.address, r]));
}

/**
 * Stalest first: never-snapshotted vaults, then oldest lastSnapshotAt. A run
 * cut short by its time budget then leaves the freshest vaults for next time
 * instead of starving the same tail on every run. Stable, so ties keep the
 * API's TVL order.
 */
function stalestFirst(vaults: MorphoVaultV2[], refs: Map<string, VaultRef>): MorphoVaultV2[] {
  const at = (v: MorphoVaultV2) => refs.get(v.address)?.lastSnapshotAt?.getTime() ?? -Infinity;
  return [...vaults].sort((a, b) => at(a) - at(b));
}

/** A vault's curator link, as upsertVault used to resolve it. */
async function linkCurator(
  vault: MorphoVaultV2,
  ctx: ChainContext
): Promise<{ curatorId: string | null; curatorCreated: boolean }> {
  // Canonical org: inline on V1 vaults; V2 resolves via the per-run registry
  const canonical =
    vault.curators?.items?.[0] ??
    (vault.curator?.address
      ? ctx.curatorRegistry.get(vault.curator.address.toLowerCase()) ?? null
      : null);
  if (vault.curator?.address) {
    // Check for vault-level curator overrides (e.g. Clearstar vaults under Re7's address)
    const resolvedCuratorAddress = resolveVaultCuratorAddress(vault.address, vault.curator.address);
    const r = await ensureCuratorExists(ctx.curators, resolvedCuratorAddress, vault.name, canonical);
    return { curatorId: r.curatorId, curatorCreated: r.created };
  }
  if (canonical && canonical.addresses.length > 0) {
    // V1 vaults occasionally report no state.curator while the registry still
    // attributes them — use the org's first known address as the curator key.
    const r = await ensureCuratorExists(ctx.curators, canonical.addresses[0].address, vault.name, canonical);
    return { curatorId: r.curatorId, curatorCreated: r.created };
  }
  return { curatorId: null, curatorCreated: false };
}

/**
 * A required Vault column the API sent as null. Checked per vault before the
 * batched writes, so one bad row fails only itself (as a per-row write did),
 * not the whole chunk's statement.
 */
function missingRequiredField(vault: MorphoVaultV2): string | null {
  if (vault.name == null) return "name";
  if (vault.symbol == null) return "symbol";
  if (vault.performanceFee == null) return "performanceFee";
  if (vault.managementFee == null) return "managementFee";
  return null;
}

/** A vault in a chunk, linked to its curator. */
interface ChunkItem {
  vault: MorphoVaultV2;
  curatorId: string | null;
  curatorCreated: boolean;
}

/** A vault whose row is written; the remaining steps key on vaultId. */
interface WrittenVault extends ChunkItem {
  vaultId: string;
}

function parseCreationTimestamp(vault: MorphoVaultV2): number | undefined {
  return vault.creationTimestamp ? parseInt(String(vault.creationTimestamp), 10) : undefined;
}

/**
 * Upsert the chunk's Vault rows: one createManyAndReturn for new vaults and
 * one UPDATE ... FROM (VALUES ...) for existing ones (same columns as the old
 * per-vault create/update). `refs` gains the created rows. Returns the vaults
 * written, and how many were skipped as a cross-chain address collision.
 */
async function writeVaultRows(
  items: ChunkItem[],
  refs: Map<string, VaultRef>,
  ctx: ChainContext
): Promise<{ written: WrittenVault[]; collisions: number }> {
  const fresh = items.filter((i) => !refs.has(i.vault.address));
  const createdIds = new Set<string>();
  if (fresh.length > 0) {
    const created = await prisma.vault.createManyAndReturn({
      data: fresh.map(({ vault, curatorId }) => ({
        address: vault.address,
        name: vault.name,
        symbol: vault.symbol,
        chainId: ctx.chainId,
        chainName: ctx.chainName,
        onchainAddress: vault.address.toLowerCase(),
        assetAddress: vault.asset.address,
        assetSymbol: vault.asset.symbol,
        assetDecimals: vault.asset.decimals,
        curatorAddress: vault.curator?.address,
        curatorId,
        performanceFee: vault.performanceFee,
        managementFee: vault.managementFee,
        warnings: JSON.parse(JSON.stringify(vault.warnings ?? [])),
        listed: vault.listed ?? true,
        creationTimestamp: parseCreationTimestamp(vault),
        pendingConfigs: JSON.parse(JSON.stringify(vault.pendingConfigs?.items ?? [])),
      })),
      select: VAULT_REF_SELECT,
      // A row another job inserted since the prefetch is updated below instead
      skipDuplicates: true,
    });
    for (const r of created) {
      refs.set(r.address, r);
      createdIds.add(r.id);
    }
    const raced = fresh.filter((i) => !refs.has(i.vault.address)).map((i) => i.vault.address);
    if (raced.length > 0) {
      for (const [address, r] of await fetchVaultRefs(raced)) refs.set(address, r);
    }
  }

  const written: WrittenVault[] = [];
  let collisions = 0;
  for (const item of items) {
    const ref = refs.get(item.vault.address);
    if (!ref) throw new Error(`Vault row missing after upsert: ${item.vault.address}`);
    // Vault.address is globally unique (not per chain). A same-address vault on a
    // different chain would clobber the original row — skip it loudly instead.
    // Morpho factories don't reuse addresses across chains today, so this should
    // stay at zero; if it ever fires, address+chainId needs a composite key.
    if (ref.chainId !== ctx.chainId) {
      log(`  ⚠ Address collision across chains, skipping: ${item.vault.address} (db chain ${ref.chainId}, api chain ${ctx.chainId})`);
      collisions++;
      continue;
    }
    written.push({ ...item, vaultId: ref.id });
  }

  const updates = written.filter((w) => !createdIds.has(w.vaultId));
  const now = new Date();
  for (let i = 0; i < updates.length; i += ROWS_PER_STATEMENT) {
    const values = updates.slice(i, i + ROWS_PER_STATEMENT).map(({ vault, curatorId, vaultId }) => Prisma.sql`(
      ${vaultId}::text, ${vault.name}::text, ${vault.symbol}::text,
      ${vault.address.toLowerCase()}::text, ${vault.curator?.address ?? null}::text, ${curatorId}::text,
      ${vault.performanceFee}::float8, ${vault.managementFee}::float8,
      ${JSON.stringify(vault.warnings ?? [])}::jsonb, ${vault.listed ?? true}::boolean,
      ${parseCreationTimestamp(vault) ?? null}::int,
      ${JSON.stringify(vault.pendingConfigs?.items ?? [])}::jsonb
    )`);
    // creationTimestamp: an absent value leaves the column as is (Prisma
    // skipped `undefined`); every other column is overwritten, as before.
    await prisma.$executeRaw`
      UPDATE "Vault" AS t
      SET "name" = v.name,
          "symbol" = v.symbol,
          "chainId" = ${ctx.chainId}::int,
          "chainName" = ${ctx.chainName}::text,
          "onchainAddress" = v.onchain_address,
          "curatorAddress" = v.curator_address,
          "curatorId" = v.curator_id,
          "performanceFee" = v.performance_fee,
          "managementFee" = v.management_fee,
          "warnings" = v.warnings,
          "listed" = v.listed,
          "creationTimestamp" = COALESCE(v.creation_timestamp, t."creationTimestamp"),
          "pendingConfigs" = v.pending_configs,
          "updatedAt" = ${now}
      FROM (VALUES ${Prisma.join(values)}) AS v(
        id, name, symbol, onchain_address, curator_address, curator_id,
        performance_fee, management_fee, warnings, listed, creation_timestamp, pending_configs
      )
      WHERE t.id = v.id
    `;
  }

  return { written, collisions };
}

function calculateSharePrice(vault: MorphoVaultV2): number {
  if (vault.sharePrice) {
    return vault.sharePrice;
  }

  const totalAssets = BigInt(vault.totalAssets || "0");
  const totalSupply = BigInt(vault.totalSupply || "1");

  if (totalSupply === 0n) {
    return 1;
  }

  return Number(totalAssets) / Number(totalSupply);
}


/**
 * Calculate USD value for a transaction based on shares and vault data.
 *
 * Key insight: ERC4626 vaults use 18 decimals for shares, but the underlying
 * asset may have different decimals (e.g., 6 for USDC).
 *
 * Formula:
 * - sharesHuman = shares / 10^18 (shares always have 18 decimals)
 * - assetsHuman = sharesHuman * sharePrice (sharePrice converts shares to assets)
 * - assetPriceUsd = totalAssetsUsd / (totalAssets / 10^assetDecimals)
 * - assetsUsd = assetsHuman * assetPriceUsd
 */
const SHARE_DECIMALS = 18; // ERC4626 standard

function calculateTransactionUsdValue(
  shares: string | null,
  sharePrice: number,
  totalAssets: string,
  totalAssetsUsd: number,
  assetDecimals: number
): { assets: string | null; assetsUsd: number | null } {
  if (!shares || !sharePrice || !totalAssets || !totalAssetsUsd) {
    return { assets: null, assetsUsd: null };
  }

  try {
    const sharesNum = parseFloat(shares);
    const totalAssetsNum = parseFloat(totalAssets);

    if (sharesNum === 0 || totalAssetsNum === 0) {
      return { assets: null, assetsUsd: null };
    }

    // Convert shares from raw to human-readable (18 decimals)
    const shareDivisor = Math.pow(10, SHARE_DECIMALS);
    const sharesHuman = sharesNum / shareDivisor;

    // Convert shares to assets using sharePrice
    // sharePrice = totalAssets(human) / totalSupply(human)
    const assetsHuman = sharesHuman * sharePrice;

    // Calculate asset price per token in USD
    const assetDivisor = Math.pow(10, assetDecimals);
    const totalAssetsHuman = totalAssetsNum / assetDivisor;
    const assetPriceUsd = totalAssetsUsd / totalAssetsHuman;

    // Calculate USD value
    const assetsUsd = assetsHuman * assetPriceUsd;

    // Store assets in raw units (with asset decimals)
    const assetsRaw = assetsHuman * assetDivisor;

    return {
      assets: assetsRaw.toString(),
      assetsUsd: Math.abs(assetsUsd), // Use absolute value since withdrawals show negative
    };
  } catch {
    return { assets: null, assetsUsd: null };
  }
}

interface VaultPriceData {
  sharePrice: number;
  totalAssets: string;
  totalAssetsUsd: number;
  assetDecimals: number;
}


/**
 * Builds one vault's snapshot row with the sanitize + phantom guards; returns
 * it with the phantom reason (null = looks real). Written by writeSnapshots.
 */
function buildSnapshot(
  vaultId: string,
  vault: MorphoVaultV2,
  baseline: PhantomBaseline | null
): { data: Prisma.VaultSnapshotCreateManyInput; phantomReason: string | null } {
  const sharePrice = calculateSharePrice(vault);

  // Calculate liquidityUsd from liquidity (raw asset units) and price
  let liquidityUsd: number | null = null;
  if (vault.liquidity && vault.totalAssets && vault.totalAssetsUsd) {
    const totalAssets = BigInt(vault.totalAssets);
    const liquidity = BigInt(vault.liquidity);
    if (totalAssets > 0n) {
      // Calculate price per unit: totalAssetsUsd / totalAssets
      // Then: liquidityUsd = liquidity * (totalAssetsUsd / totalAssets)
      liquidityUsd = Number(liquidity) * (vault.totalAssetsUsd / Number(totalAssets));
    }
  }

  // Sanity check: reject absurd APY values from the Morpho API. avgApy may be
  // undefined (VaultV2.avgApy is no longer served) — normalize so it isn't
  // logged as "bad".
  const rawAvgApy = vault.avgApy ?? null;
  const sanitizedAvgApy = sanitizeApyForStorage(rawAvgApy);
  const sanitizedAvgNetApy = sanitizeApyForStorage(vault.avgNetApy);

  if (sanitizedAvgApy !== rawAvgApy || sanitizedAvgNetApy !== vault.avgNetApy) {
    log(`  ⚠ Rejected bad APY for ${vaultId}: avgApy=${vault.avgApy}, avgNetApy=${vault.avgNetApy}`);
  }
  // Same guard for the instantaneous APYs (a market stuck at 100% utilization
  // reports the IRM ceiling, 2979.96 = e^8 - 1).
  const sanitizedApy = sanitizeApyForStorage(vault.apy);
  const sanitizedNetApy = sanitizeApyForStorage(vault.netApy);

  const phantomReason = assessPhantom({
    apy: vault.apy,
    netApy: vault.netApy,
    sharePrice,
    assetSymbol: vault.asset.symbol,
    totalAssets: vault.totalAssets != null ? String(vault.totalAssets) : null,
    totalSupply: vault.totalSupply != null ? String(vault.totalSupply) : null,
    baseline,
  });
  if (phantomReason) {
    log(`  ⚠ Phantom accrual, not counted in totals: ${vault.name} (${phantomReason})`);
  }

  return {
    data: {
      vaultId,
      totalAssets: String(vault.totalAssets),
      totalAssetsUsd: vault.totalAssetsUsd ?? 0,
      totalSupply: String(vault.totalSupply),
      sharePrice,
      liquidity: vault.liquidity ? String(vault.liquidity) : null,
      liquidityUsd,
      apy: sanitizedApy,
      netApy: sanitizedNetApy,
      avgApy: sanitizedAvgApy,
      avgNetApy: sanitizedAvgNetApy,
    },
    phantomReason,
  };
}

/**
 * Batched recordSnapshotWritten() (data-quality/maintenance.ts): stamp
 * lastSnapshotAt and set/clear the 'phantom' flag for every vault just
 * snapshotted, in one statement with the same CASE rules.
 */
async function recordSnapshotsWritten(
  rows: { vaultId: string; phantom: boolean }[],
  at: Date = new Date()
): Promise<void> {
  const values = rows.map((r) => Prisma.sql`(${r.vaultId}::text, ${r.phantom}::boolean)`);
  await prisma.$executeRaw`
    UPDATE "Vault" AS t
    SET "lastSnapshotAt" = ${at},
        "countInTotals" = CASE WHEN v.phantom THEN false
                               WHEN t."excludeReason" = 'phantom' THEN true
                               ELSE t."countInTotals" END,
        "excludeReason" = CASE WHEN v.phantom THEN 'phantom'
                               WHEN t."excludeReason" = 'phantom' THEN NULL
                               ELSE t."excludeReason" END
    FROM (VALUES ${Prisma.join(values)}) AS v(id, phantom)
    WHERE t.id = v.id
  `;
}

/**
 * Write the chunk's snapshots (one createMany), then stamp lastSnapshotAt +
 * the phantom flag (one UPDATE). Returns the phantom-flagged vault ids.
 */
async function writeSnapshots(written: WrittenVault[], ctx: ChainContext): Promise<Set<string>> {
  const built = written.map((w) => ({
    vaultId: w.vaultId,
    ...buildSnapshot(w.vaultId, w.vault, ctx.phantomBaselines.get(w.vaultId) ?? null),
  }));
  await prisma.vaultSnapshot.createMany({ data: built.map((b) => b.data) });
  await recordSnapshotsWritten(built.map((b) => ({ vaultId: b.vaultId, phantom: b.phantomReason !== null })));
  return new Set(built.filter((b) => b.phantomReason !== null).map((b) => b.vaultId));
}

type AllocationRow = Prisma.AdapterAllocationCreateManyInput & {
  adapterAddress: string;
  adapterType: string;
  assets: string;
  assetsUsd: number;
  allocationPct: number;
};

/** Adapter allocations for the chunk (one createMany); rows by vault id. */
async function writeAdapterAllocations(
  written: WrittenVault[],
  snapshotTime: Date
): Promise<Map<string, AllocationRow[]>> {
  const byVault = new Map<string, AllocationRow[]>();
  for (const { vaultId, vault } of written) {
    const totalAssetsUsd = vault.totalAssetsUsd || 0;
    byVault.set(
      vaultId,
      vault.adapters.items.map((adapter) => ({
        vaultId,
        adapterAddress: adapter.address,
        adapterType: adapter.type,
        assets: String(adapter.assets),
        assetsUsd: adapter.assetsUsd ?? 0,
        allocationPct:
          totalAssetsUsd > 0 ? (adapter.assetsUsd / totalAssetsUsd) * 100 : 0,
        snapshotTime,
      }))
    );
  }

  const rows = [...byVault.values()].flat();
  for (let i = 0; i < rows.length; i += ROWS_PER_STATEMENT) {
    await prisma.adapterAllocation.createMany({ data: rows.slice(i, i + ROWS_PER_STATEMENT) });
  }
  return byVault;
}

/** Run `fn` over `items` with at most `limit` calls in flight; keeps order. */
async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<R>
): Promise<R[]> {
  const out = new Array<R>(items.length);
  let next = 0;
  const worker = async () => {
    while (next < items.length) {
      const i = next++;
      out[i] = await fn(items[i]);
    }
  };
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return out;
}

/**
 * Fetch and store the chunk's recent transactions. Same result as the old
 * per-tx upsert (insert new rows; refresh assets/assetsUsd on existing ones),
 * in one createMany + one UPDATE per ROWS_PER_STATEMENT rows.
 */
async function collectTransactions(written: WrittenVault[]): Promise<number> {
  const fetched = await mapWithConcurrency(written, API_CONCURRENCY, (w) =>
    fetchVaultTransactions(w.vault.address)
  );

  // Per (vaultId, txHash): a serial upsert inserts the first occurrence and
  // then overwrites assets/assetsUsd with each later one.
  const inserts = new Map<string, Prisma.VaultTransactionCreateManyInput>();
  const usdUpdates = new Map<
    string,
    { vaultId: string; txHash: string; assets: string | null; assetsUsd: number | null }
  >();
  let stored = 0;
  written.forEach(({ vaultId, vault }, i) => {
    const vaultPriceData: VaultPriceData = {
      sharePrice: vault.sharePrice || calculateSharePrice(vault),
      totalAssets: String(vault.totalAssets),
      totalAssetsUsd: vault.totalAssetsUsd || 0,
      assetDecimals: vault.asset.decimals,
    };
    for (const tx of fetched[i]) {
      // Calculate USD value from shares
      const { assets, assetsUsd } = calculateTransactionUsdValue(
        tx.shares,
        vaultPriceData.sharePrice,
        vaultPriceData.totalAssets,
        vaultPriceData.totalAssetsUsd,
        vaultPriceData.assetDecimals
      );
      const key = `${vaultId}|${tx.txHash}`;
      if (!inserts.has(key)) {
        inserts.set(key, {
          vaultId,
          txHash: tx.txHash,
          blockNumber: tx.blockNumber,
          timestamp: new Date(Number(tx.timestamp) * 1000),
          type: tx.type,
          shares: tx.shares != null ? String(tx.shares) : null,
          assets,
          assetsUsd,
        });
      }
      usdUpdates.set(key, { vaultId, txHash: tx.txHash, assets, assetsUsd });
      stored++;
    }
  });

  const insertRows = [...inserts.values()];
  for (let i = 0; i < insertRows.length; i += ROWS_PER_STATEMENT) {
    await prisma.vaultTransaction.createMany({
      data: insertRows.slice(i, i + ROWS_PER_STATEMENT),
      skipDuplicates: true,
    });
  }

  // Update USD values for existing transactions (a no-op rewrite for the rows
  // just inserted).
  const updateRows = [...usdUpdates.values()];
  for (let i = 0; i < updateRows.length; i += ROWS_PER_STATEMENT) {
    const values = updateRows
      .slice(i, i + ROWS_PER_STATEMENT)
      .map((u) => Prisma.sql`(${u.vaultId}::text, ${u.txHash}::text, ${u.assets}::text, ${u.assetsUsd}::float8)`);
    await prisma.$executeRaw`
      UPDATE "VaultTransaction" AS t
      SET "assets" = v.assets, "assetsUsd" = v.assets_usd
      FROM (VALUES ${Prisma.join(values)}) AS v(vault_id, tx_hash, assets, assets_usd)
      WHERE t."vaultId" = v.vault_id AND t."txHash" = v.tx_hash
    `;
  }

  return stored;
}

/** Identity of a reallocation event (no unique id is stored). */
function reallocationKey(r: {
  vaultId: string;
  txHash: string | null;
  marketId: string | null;
  type: string | null;
  amount: string;
}): string {
  return [r.vaultId, r.txHash, r.marketId, r.type, r.amount].join("|");
}

/**
 * Fetch and store the chunk's recent reallocations, skipping events already
 * stored: the API returns the latest TRANSACTIONS_PER_VAULT on every full run,
 * so plain inserts duplicated them run after run. VaultReallocation has no
 * unique constraint in the schema; prisma/manual-sql/2026-09-30-vault-
 * reallocation-unique.sql adds one on the same key, which skipDuplicates then
 * also honors under a concurrent writer.
 */
async function collectReallocations(written: WrittenVault[]): Promise<number> {
  const fetched = await mapWithConcurrency(written, API_CONCURRENCY, (w) =>
    fetchVaultReallocations(w.vault.address)
  );

  const rows: Prisma.VaultReallocationCreateManyInput[] = [];
  written.forEach(({ vaultId }, i) => {
    for (const realloc of fetched[i]) {
      rows.push({
        vaultId,
        timestamp: new Date(Number(realloc.timestamp) * 1000),
        txHash: realloc.hash,
        type: realloc.type,
        marketId: realloc.market?.marketId ?? null,
        // The API serves `assets` as a JSON number; the column is text.
        amount: String(realloc.assets),
      });
    }
  });
  if (rows.length === 0) return 0;

  const existing = await prisma.vaultReallocation.findMany({
    where: {
      vaultId: { in: [...new Set(rows.map((r) => r.vaultId))] },
      txHash: { in: [...new Set(rows.map((r) => r.txHash).filter((h): h is string => h != null))] },
    },
    select: { vaultId: true, txHash: true, marketId: true, type: true, amount: true },
  });
  const seen = new Set(existing.map(reallocationKey));
  const fresh = rows.filter((r) => {
    const key = reallocationKey({
      vaultId: r.vaultId,
      txHash: r.txHash ?? null,
      marketId: r.marketId ?? null,
      type: r.type ?? null,
      amount: r.amount,
    });
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  let stored = 0;
  for (let i = 0; i < fresh.length; i += ROWS_PER_STATEMENT) {
    const res = await prisma.vaultReallocation.createMany({
      data: fresh.slice(i, i + ROWS_PER_STATEMENT),
      skipDuplicates: true,
    });
    stored += res.count;
  }
  return stored;
}

/** Risk snapshots for the chunk (one createMany), from its allocations. */
async function writeRiskSnapshots(
  written: WrittenVault[],
  allocationsByVault: Map<string, AllocationRow[]>
): Promise<void> {
  const data = written.map(({ vaultId, vault }) => {
    const allocations = allocationsByVault.get(vaultId) ?? [];
    const totalAssetsUsd = vault.totalAssetsUsd || 0;
    const totalAssets = BigInt(vault.totalAssets || "0");

    // Calculate idle assets
    const allocatedAssets = allocations.reduce(
      (sum, a) => sum + BigInt(a.assets),
      0n
    );
    const idleAssets = totalAssets - allocatedAssets;
    const idleAssetsPercent =
      totalAssets > 0n ? (Number(idleAssets) / Number(totalAssets)) * 100 : 0;

    // Calculate risk metrics
    const riskMetrics = calculateAllRiskMetrics(
      allocations.map((a) => ({
        address: a.adapterAddress,
        type: a.adapterType,
        assets: a.assets,
        assetsUsd: a.assetsUsd,
        allocationPct: a.allocationPct,
      })),
      idleAssetsPercent,
      totalAssetsUsd
    );

    return {
      vaultId,
      topAdapterPercent: riskMetrics.topAdapterPercent,
      top3AdaptersPercent: riskMetrics.top3AdaptersPercent,
      herfindahlIndex: riskMetrics.herfindahlIndex,
      numActiveAdapters: riskMetrics.numActiveAdapters,
      idleAssetsPercent: riskMetrics.idleAssetsPercent,
      hasLiquidityAdapter: riskMetrics.hasLiquidityAdapter,
      avgAllocationPercent: riskMetrics.avgAllocationPercent,
      largestAllocation: riskMetrics.largestAllocation,
      concentrationScore: riskMetrics.concentrationScore,
      liquidityScore: riskMetrics.liquidityScore,
      diversificationScore: riskMetrics.diversificationScore,
    };
  });
  await prisma.vaultRiskSnapshot.createMany({ data });
}

interface BatchResult {
  processed: number;
  curatorsCreated: number;
  txCollected: number;
  reallocsCollected: number;
  changesDetected: number;
  phantomFlagged: number;
  errors: string[];
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

/**
 * Process one chunk of vaults: upsert, snapshot, allocations, transactions,
 * reallocations, risk metrics, change detection — each step one statement (or
 * a few) for the whole chunk instead of one per vault. A failed statement
 * fails every vault in the chunk (reported per vault), like a failed per-vault
 * write failed that vault; the next chunk still runs.
 */
async function processChunk(
  vaults: MorphoVaultV2[],
  refs: Map<string, VaultRef>,
  snapshotTime: Date,
  options: CollectionOptions,
  ctx: ChainContext
): Promise<BatchResult> {
  const result: BatchResult = {
    processed: 0,
    curatorsCreated: 0,
    txCollected: 0,
    reallocsCollected: 0,
    changesDetected: 0,
    phantomFlagged: 0,
    errors: [],
  };

  // Curator links: in memory, bar the rare create/rename
  const items: ChunkItem[] = [];
  for (const vault of vaults) {
    const ref = refs.get(vault.address);
    if (ref && ref.chainId !== ctx.chainId) {
      // Cross-chain address collision: skipped before any write (see writeVaultRows)
      log(`  ⚠ Address collision across chains, skipping: ${vault.address} (db chain ${ref.chainId}, api chain ${ctx.chainId})`);
      result.processed++;
      continue;
    }
    try {
      const missing = missingRequiredField(vault);
      if (missing) throw new Error(`API returned no ${missing}`);
      items.push({ vault, ...(await linkCurator(vault, ctx)) });
    } catch (error) {
      result.errors.push(`${vault.name}: ${errorMessage(error)}`);
    }
  }
  if (items.length === 0) return result;

  let written: WrittenVault[];
  let phantomIds: Set<string>;
  try {
    // Upsert vault records
    const upsert = await writeVaultRows(items, refs, ctx);
    written = upsert.written;
    result.processed += upsert.collisions; // skipped, as before: not an error
    if (written.length === 0) return result;

    // Create snapshots (+ stamp lastSnapshotAt, set/clear the phantom flag)
    phantomIds = await writeSnapshots(written, ctx);

    // Store adapter allocations (V1 has no adapters — allocation is market-level)
    const allocationsByVault = ctx.isV1
      ? new Map<string, AllocationRow[]>()
      : await writeAdapterAllocations(written, snapshotTime);

    // Fetch and store transactions (unless skipped; V2-only endpoint)
    if (!options.skipTransactions && !ctx.isV1) {
      result.txCollected = await collectTransactions(written);
    }

    // Fetch and store reallocations (unless skipped; V2-only endpoint)
    if (!options.skipReallocations && !ctx.isV1) {
      result.reallocsCollected = await collectReallocations(written);
    }

    // Create risk snapshots. Skipped for V1: with no adapter data every metric
    // would read "100% idle / zero diversification", which is a data artifact,
    // not a risk signal.
    if (!ctx.isV1) {
      await writeRiskSnapshots(written, allocationsByVault);
    }
  } catch (error) {
    const msg = errorMessage(error);
    logError(`Chunk of ${items.length} ${ctx.chainName} vaults failed`, error);
    for (const { vault } of items) result.errors.push(`${vault.name}: ${msg}`);
    result.txCollected = 0;
    result.reallocsCollected = 0;
    return result;
  }

  result.processed += written.length;
  result.phantomFlagged = phantomIds.size;
  result.curatorsCreated = written.filter((w) => w.curatorCreated).length;

  // Detect and store changes (non-critical: a failure never fails the vaults)
  try {
    const changes = await detectAlertsBatch(
      written.map(({ vaultId, vault }) => ({
        vault: {
          id: vaultId,
          name: vault.name,
          symbol: vault.symbol,
          assetSymbol: vault.asset.symbol,
          assetDecimals: vault.asset.decimals,
          curatorAddress: vault.curator?.address ?? "",
          creationTimestamp: parseCreationTimestamp(vault) ?? null,
        },
        snapshot: {
          totalAssets: String(vault.totalAssets),
          totalAssetsUsd: vault.totalAssetsUsd || 0,
          sharePrice: vault.sharePrice || 1,
          avgApy: vault.avgApy || null,
          timestamp: snapshotTime,
        },
      }))
    );
    if (changes.length > 0) {
      result.changesDetected = await storeChanges(changes);
    }
  } catch (error) {
    logError(`Change detection failed for a chunk of ${written.length} vaults (non-critical)`, error);
  }

  return result;
}

/**
 * Process vaults in chunks of CHUNK_SIZE, stalest first. Stops starting new
 * chunks once `deadline` passes; the rest are reported as deferred.
 */
async function processVaultsBatch(
  vaults: MorphoVaultV2[],
  snapshotTime: Date,
  options: CollectionOptions,
  ctx: ChainContext,
  deadline: number
): Promise<BatchResult & { deferred: number }> {
  const total: BatchResult & { deferred: number } = {
    processed: 0,
    curatorsCreated: 0,
    txCollected: 0,
    reallocsCollected: 0,
    changesDetected: 0,
    phantomFlagged: 0,
    errors: [],
    deferred: 0,
  };

  const refs = await fetchVaultRefs(vaults.map((v) => v.address));
  const ordered = stalestFirst(vaults, refs);

  for (let i = 0; i < ordered.length; i += CHUNK_SIZE) {
    if (Date.now() > deadline) {
      total.deferred = ordered.length - i;
      break;
    }
    const r = await processChunk(ordered.slice(i, i + CHUNK_SIZE), refs, snapshotTime, options, ctx);
    total.processed += r.processed;
    total.curatorsCreated += r.curatorsCreated;
    total.txCollected += r.txCollected;
    total.reallocsCollected += r.reallocsCollected;
    total.changesDetected += r.changesDetected;
    total.phantomFlagged += r.phantomFlagged;
    total.errors.push(...r.errors);

    if (options.verbose) {
      log(`  Processed ${Math.min(i + CHUNK_SIZE, ordered.length)}/${ordered.length} vaults`);
    }
  }

  return total;
}

/**
 * Main data collection function.
 * Fetches all vaults from Morpho API and stores snapshots, transactions, and risk data.
 */
/**
 * Active Morpho vaults the DB tracks for one chain + generation. Vault has no
 * generation column; V2 is told apart by its risk snapshots (only V2 vaults get
 * them — see processChunk). Only called when a source comes back empty.
 */
async function countTrackedVaults(chainId: number, isV1: boolean): Promise<number> {
  return prisma.vault.count({
    where: {
      dataSource: "morpho",
      active: true,
      chainId,
      riskSnapshots: isV1 ? { none: {} } : { some: {} },
    },
  });
}

export async function collectData(options: CollectionOptions = {}): Promise<CollectionResult> {
  const startTime = Date.now();
  const errors: string[] = [];
  const sourceErrors: string[] = [];
  const minTvlUsd = options.minTvlUsd ?? MIN_TVL_USD;

  log("=".repeat(60));
  log("Starting data collection...");
  log(`Options: fetchAll=${options.fetchAll ?? true}, minTvl=$${minTvlUsd}, skipTx=${options.skipTransactions ?? false}`);

  try {
    const snapshotTime = new Date();

    // Aggregate across chains and vault generations
    let totalValid = 0;
    let skippedCount = 0;
    const result = {
      processed: 0,
      curatorsCreated: 0,
      txCollected: 0,
      reallocsCollected: 0,
      changesDetected: 0,
      phantomFlagged: 0,
    };

    // Canonical curator identities, fetched once and shared by every chain
    const curatorRegistry = await fetchMorphoCuratorRegistry();

    // ~30-day-old snapshots for the phantom-accrual test (one query per run)
    const phantomBaselines = await fetchPhantomBaselines("morpho");

    // Every curator row, so resolving a vault's curator needs no query
    const curators = await loadCuratorCache();

    const deadline = startTime + (options.timeBudgetMs ?? Infinity);

    // Each chain is fetched and processed independently: one chain's API
    // trouble must not take down the whole collection run.
    const chains = options.chainIds
      ? MORPHO_CHAINS.filter((c) => options.chainIds!.includes(c.chainId))
      : MORPHO_CHAINS;
    for (const chain of chains) {
      const chainName = canonicalChainName(chain.chainId);
      const chainMinTvl = effectiveMinTvl(chain, options);

      const generations = options.generations ?? ["v2", "v1"];
      for (const isV1 of [false, true]) {
        if (!generations.includes(isV1 ? "v1" : "v2")) continue;
        const ctx: ChainContext = { chainId: chain.chainId, chainName, isV1, curatorRegistry, phantomBaselines, curators };
        const label = `${chainName} ${isV1 ? "V1" : "V2"}`;

        if (Date.now() > deadline) {
          const msg = `${label}: not collected, run time budget reached`;
          logError(msg);
          errors.push(msg);
          sourceErrors.push(msg);
          continue;
        }

        try {
          const pageErrors: string[] = [];
          const fetched = isV1
            ? await fetchAllVaultsV1(chain, options, pageErrors)
            : await fetchAllVaults(chain, options, pageErrors);
          // A later page failed: process what was fetched, but the run is not
          // clean — the tail of the list keeps its old snapshot.
          for (const e of pageErrors) {
            const msg = `${label}: ${e}`;
            logError(msg);
            errors.push(msg);
            sourceErrors.push(msg);
          }

          // Validate and filter vaults
          const validVaults: MorphoVaultV2[] = [];
          const seenAddresses = new Set<string>();
          for (const vault of fetched) {
            const validation = isValidVault(vault, chainMinTvl);
            if (validation.valid && seenAddresses.has(vault.address)) {
              // skip-based paging can serve a vault on two pages when TVLs
              // shift mid-fetch; write it once
              skippedCount++;
              log(`  Skipped duplicate ${vault.name || vault.address} (served twice by the API)`);
            } else if (validation.valid) {
              seenAddresses.add(vault.address);
              validVaults.push(vault);
            } else {
              skippedCount++;
              if (options.verbose) {
                log(`  Skipped ${vault.name || vault.address}: ${validation.reason}`);
              }
            }
          }
          totalValid += validVaults.length;

          if (validVaults.length === 0) {
            // An empty answer for a chain we track is a broken source (e.g. a
            // query that "succeeds" with nothing), not an empty market.
            const tracked = await countTrackedVaults(chain.chainId, isV1);
            if (tracked > EMPTY_SOURCE_DB_THRESHOLD) {
              const msg = `${label}: API returned 0 vaults but DB tracks ${tracked} active`;
              logError(msg);
              errors.push(msg);
              sourceErrors.push(msg);
            }
            continue;
          }
          log(`Processing ${validVaults.length} ${label} vaults...`);

          const batchResult = await processVaultsBatch(validVaults, snapshotTime, options, ctx, deadline);
          errors.push(...batchResult.errors);
          if (batchResult.processed === 0 && batchResult.deferred < validVaults.length) {
            sourceErrors.push(`${label}: all ${validVaults.length} vaults failed processing`);
          }
          if (batchResult.deferred > 0) {
            // Fail loud: these keep their old snapshot until the next run
            // (stalest first, so they lead it).
            const msg = `${label}: run time budget reached, ${batchResult.deferred}/${validVaults.length} vaults deferred`;
            logError(msg);
            errors.push(msg);
            sourceErrors.push(msg);
          }
          result.processed += batchResult.processed;
          result.curatorsCreated += batchResult.curatorsCreated;
          result.txCollected += batchResult.txCollected;
          result.reallocsCollected += batchResult.reallocsCollected;
          result.changesDetected += batchResult.changesDetected;
          result.phantomFlagged += batchResult.phantomFlagged;
        } catch (error) {
          const msg = `${label} collection failed: ${error instanceof Error ? error.message : error}`;
          logError(msg);
          errors.push(msg);
          sourceErrors.push(msg);
        }
      }
    }

    log(`Processed: ${result.processed}/${totalValid} vaults across ${chains.length} chain(s)`);

    // Totals hygiene: wrapper/bridged/nested/cross-source flags, then
    // curator stats over counted vaults only.
    log("Applying exclusion rules + updating curator statistics...");
    const hygiene = await finalizeCollection();
    log(`  Exclusion flags changed: ${hygiene.changed} (${JSON.stringify(hygiene.excludedByReason)})`);
    log(`  Curator stats updated: ${hygiene.curatorsUpdated} curators`);

    // Curator & ecosystem-level alert detection
    let platformAlertsDetected = 0;
    let curatorSnapshotsCreated = 0;
    try {
      // 1. Create curator snapshots (for AUM history)
      curatorSnapshotsCreated = await createCuratorSnapshots();
      log(`  Curator snapshots created: ${curatorSnapshotsCreated}`);

      // 2. Detect curator-level alerts
      const curatorAlerts = await detectCuratorAlerts();
      if (curatorAlerts.length > 0) {
        const stored = await storePlatformAlerts(curatorAlerts);
        platformAlertsDetected += stored;
        log(`  Curator alerts: ${stored} stored (${curatorAlerts.length} detected)`);
      }

      // 3. Detect ecosystem-level alerts
      const ecosystemAlerts = await detectEcosystemAlerts();
      if (ecosystemAlerts.length > 0) {
        const stored = await storePlatformAlerts(ecosystemAlerts);
        platformAlertsDetected += stored;
        log(`  Ecosystem alerts: ${stored} stored (${ecosystemAlerts.length} detected)`);
      }

      // 4. Cleanup old snapshots (cheap operation)
      const cleaned = await cleanupOldCuratorSnapshots();
      if (cleaned > 0) {
        log(`  Cleaned up ${cleaned} old curator snapshots`);
      }
    } catch (error) {
      logError("Failed to run curator/ecosystem alert detection (non-critical)", error);
    }

    // Collect market allocations (needed for liquidation join)
    if (!options.skipMarketAllocations) {
      log("Collecting market allocations...");
      try {
        const maResult = await collectMarketAllocations();
        log(`  Market allocations: ${maResult.allocationsStored} stored from ${maResult.vaultsProcessed} vaults`);
      } catch (error) {
        logError("Failed to collect market allocations (non-critical)", error);
      }
    }

    // Collect liquidation data
    if (!options.skipLiquidations) {
      log("Collecting liquidation data...");
      try {
        const liqResult = await collectLiquidations();
        log(`  Liquidations: ${liqResult.stored} new, ${liqResult.fetched} fetched`);
      } catch (error) {
        logError("Failed to collect liquidations (non-critical)", error);
      }
    }

    // Print summary
    log("-".repeat(60));
    log("Data collection completed!");
    log(`  Vaults processed: ${result.processed}/${totalValid}`);
    log(`  Vaults skipped: ${skippedCount}`);
    log(`  Curators created: ${result.curatorsCreated}`);
    log(`  Transactions collected: ${result.txCollected}`);
    log(`  Reallocations collected: ${result.reallocsCollected}`);
    log(`  Changes detected: ${result.changesDetected}`);
    log(`  Phantom accrual flagged (not counted): ${result.phantomFlagged}`);
    log(`  Platform alerts detected: ${platformAlertsDetected}`);
    log(`  Curator snapshots created: ${curatorSnapshotsCreated}`);

    // Table totals: ten full COUNT(*)s (~0.5-0.8s each on the snapshot
    // tables) — verbose runs only, not every cron lane.
    if (options.verbose) {
      log("-".repeat(60));
      log("Database totals:");
      log(`  Vaults: ${await prisma.vault.count()}`);
      log(`  Curators: ${await prisma.curator.count()}`);
      log(`  Snapshots: ${await prisma.vaultSnapshot.count()}`);
      log(`  Allocations: ${await prisma.adapterAllocation.count()}`);
      log(`  Transactions: ${await prisma.vaultTransaction.count()}`);
      log(`  Reallocations: ${await prisma.vaultReallocation.count()}`);
      log(`  Risk Snapshots: ${await prisma.vaultRiskSnapshot.count()}`);
      log(`  Changes: ${await prisma.vaultChange.count()}`);
      log(`  Platform Alerts: ${await prisma.platformAlert.count()}`);
      log(`  Curator Snapshots: ${await prisma.curatorSnapshot.count()}`);
    }

    if (errors.length > 0) {
      log(`  Errors: ${errors.length}`);
      errors.slice(0, 5).forEach((e) => log(`    - ${e}`));
      if (errors.length > 5) {
        log(`    ... and ${errors.length - 5} more`);
      }
    }

    const duration = Date.now() - startTime;
    log(`  Duration: ${(duration / 1000).toFixed(1)}s`);
    log("=".repeat(60));

    return {
      success: errors.length === 0,
      vaultsProcessed: result.processed,
      vaultsSkipped: skippedCount,
      curatorsCreated: result.curatorsCreated,
      snapshotsCreated: result.processed,
      transactionsCollected: result.txCollected,
      reallocationsCollected: result.reallocsCollected,
      riskSnapshotsCreated: result.processed,
      changesDetected: result.changesDetected,
      platformAlertsDetected,
      curatorSnapshotsCreated,
      phantomFlagged: result.phantomFlagged,
      errors,
      sourceErrors,
      duration,
    };
  } catch (error) {
    const errorMsg = `Critical error during collection: ${error}`;
    logError(errorMsg);
    errors.push(errorMsg);
    sourceErrors.push(errorMsg);

    return {
      success: false,
      vaultsProcessed: 0,
      vaultsSkipped: 0,
      curatorsCreated: 0,
      snapshotsCreated: 0,
      transactionsCollected: 0,
      reallocationsCollected: 0,
      riskSnapshotsCreated: 0,
      changesDetected: 0,
      platformAlertsDetected: 0,
      curatorSnapshotsCreated: 0,
      phantomFlagged: 0,
      errors,
      sourceErrors,
      duration: Date.now() - startTime,
    };
  }
}

/**
 * CLI entry point - runs collection and exits.
 */
async function main() {
  // Parse command line arguments
  const args = process.argv.slice(2);
  const options: CollectionOptions = {
    fetchAll: true,
    skipTransactions: args.includes("--skip-tx"),
    skipReallocations: args.includes("--skip-realloc"),
    verbose: args.includes("--verbose") || args.includes("-v"),
  };

  // Parse --min-tvl=X argument
  const minTvlArg = args.find((a) => a.startsWith("--min-tvl="));
  if (minTvlArg) {
    options.minTvlUsd = parseInt(minTvlArg.split("=")[1], 10);
  }

  try {
    const result = await collectData(options);

    if (!result.success) {
      console.error("Collection completed with errors:", result.errors);
      process.exit(1);
    }

    process.exit(0);
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

// Only run main() if this file is executed directly
const isDirectRun = require.main === module;
if (isDirectRun) {
  main();
}
