import { PrismaClient } from '@prisma/client';
import {
  extractCuratorFromVaultName,
  isAutogeneratedCuratorName,
  runExtractionTests
} from '../lib/utils/extract-curator-name';

const prisma = new PrismaClient();

async function fixCuratorNames() {
  console.log('=== Curator Name Extraction Fix ===\n');

  // First, run tests to verify extraction logic
  console.log('Running extraction tests...');
  const testResults = runExtractionTests();
  console.log(`Tests: ${testResults.passed} passed, ${testResults.failed} failed`);

  if (testResults.failed > 0) {
    console.log('\nFailed tests:');
    testResults.results
      .filter(r => r.startsWith('✗'))
      .forEach(r => console.log(`  ${r}`));
  }

  console.log('\n--- Finding curators with missing/auto-generated names ---\n');

  // Get all curators with their vaults
  const curators = await prisma.curator.findMany({
    include: {
      vaults: {
        select: { name: true },
        take: 5 // Get a few vaults to find the best name
      }
    }
  });

  const curatorsToFix = curators.filter(c => isAutogeneratedCuratorName(c.name));

  console.log(`Found ${curatorsToFix.length} curators to fix out of ${curators.length} total\n`);

  let updated = 0;
  let skipped = 0;

  for (const curator of curatorsToFix) {
    if (curator.vaults.length === 0) {
      console.log(`⚠ ${curator.address.slice(0, 10)}... - No vaults, skipping`);
      skipped++;
      continue;
    }

    // Try to extract from each vault name, pick the most common or first good one
    const extractedNames: Record<string, number> = {};

    for (const vault of curator.vaults) {
      const extracted = extractCuratorFromVaultName(vault.name);
      extractedNames[extracted] = (extractedNames[extracted] || 0) + 1;
    }

    // Pick the most common extracted name
    const sortedNames = Object.entries(extractedNames)
      .sort((a, b) => b[1] - a[1]);

    const bestName = sortedNames[0]?.[0];

    if (bestName && bestName.length >= 2) {
      await prisma.curator.update({
        where: { id: curator.id },
        data: { name: bestName }
      });

      console.log(`✓ ${curator.address.slice(0, 10)}... → "${bestName}" (from: "${curator.vaults[0].name}")`);
      updated++;
    } else {
      console.log(`⚠ ${curator.address.slice(0, 10)}... - Could not extract name from "${curator.vaults[0]?.name}"`);
      skipped++;
    }
  }

  console.log('\n=== Summary ===');
  console.log(`Updated: ${updated}`);
  console.log(`Skipped: ${skipped}`);
  console.log(`Total curators: ${curators.length}`);

  // Show final state
  console.log('\n--- Current Curator Names ---\n');
  const updatedCurators = await prisma.curator.findMany({
    select: {
      name: true,
      address: true,
      _count: { select: { vaults: true } }
    },
    orderBy: { vaults: { _count: 'desc' } },
    take: 20
  });

  updatedCurators.forEach(c => {
    console.log(`${c.name || 'NO NAME'} (${c._count.vaults} vaults) - ${c.address.slice(0, 10)}...`);
  });
}

fixCuratorNames()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
