"use client";

import { useState, useEffect } from "react";
import { formatCurrency } from "@/lib/utils/format";
import { PageHeader } from "@/components/layout/PageHeader";
import { CuratorFeesGrid, VaultFeesGrid } from "@/components/grid/FeesGrid";

interface VaultFeeData {
  vaultId: string;
  vaultAddress: string;
  vaultName: string;
  protocol?: string;
  assetSymbol: string;
  curatorName: string | null;
  curatorAddress: string | null;
  tvl: number;
  apy: number;
  performanceFee: number;
  managementFee: number;
  annualizedCuratorFees: number;
  annualizedMorphoFees: number;
  annualizedTotalFees: number;
}

interface CuratorFeeData {
  curatorId: string;
  curatorName: string;
  curatorAddress: string;
  vaultCount: number;
  totalAUM: number;
  avgPerformanceFee: number;
  avgManagementFee: number;
  annualizedCuratorFees: number;
  annualizedMorphoFees: number;
  annualizedTotalFees: number;
}

interface FeeSummary {
  totalVaults: number;
  totalCurators: number;
  estimated: {
    curatorFees: number;
    morphoFees: number;
    totalFees: number;
  };
  annualized: {
    curatorFees: number;
    morphoFees: number;
    totalFees: number;
  };
}

type ViewMode = "curators" | "vaults";

export default function FeesPage() {
  const [summary, setSummary] = useState<FeeSummary | null>(null);
  const [curatorFees, setCuratorFees] = useState<CuratorFeeData[]>([]);
  const [vaultFees, setVaultFees] = useState<VaultFeeData[]>([]);
  const [loading, setLoading] = useState(true);
  const [viewMode, setViewMode] = useState<ViewMode>("curators");

  useEffect(() => {
    async function fetchData() {
      try {
        const response = await fetch("/api/stats/fees-breakdown");
        const data = await response.json();
        if (data.success) {
          setSummary(data.data.summary);
          setCuratorFees(data.data.byCurator);
          setVaultFees(data.data.byVault);
        }
      } catch (err) {
        console.error("Failed to fetch fees:", err);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, []);

  if (loading) {
    return (
      <>
        <PageHeader title="Fee Analytics" description="Estimated fees generated by vaults and curators" breadcrumbs={[{ label: "Dashboard", href: "/" }, { label: "Fees" }]} />
        <div className="animate-pulse space-y-4">
          <div className="h-8 w-48 bg-background-elevated rounded" />
          <div className="grid grid-cols-3 gap-4">
            <div className="h-24 bg-background-elevated rounded-xl" />
            <div className="h-24 bg-background-elevated rounded-xl" />
            <div className="h-24 bg-background-elevated rounded-xl" />
          </div>
          <div className="h-64 bg-background-elevated rounded-xl" />
        </div>
      </>
    );
  }

  return (
    <>
      <PageHeader title="Fee Analytics" description="Estimated fees generated by vaults and curators" breadcrumbs={[{ label: "Dashboard", href: "/" }, { label: "Fees" }]} />

        {/* Summary Cards */}
        {summary && (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
            <SummaryCard
              label="Curator Fees (Annualized)"
              value={formatCurrency(summary.annualized.curatorFees)}
              subtext="Management + Performance"
              highlight
            />
            <SummaryCard
              label="Protocol Fees (Annualized)"
              value={formatCurrency(summary.annualized.morphoFees)}
              subtext="Morpho vaults only (15% of interest)"
            />
            <SummaryCard
              label="Total Fees (Annualized)"
              value={formatCurrency(summary.annualized.totalFees)}
              subtext="All fees combined"
            />
            <SummaryCard
              label="Tracked"
              value={`${summary.totalVaults} vaults`}
              subtext={`from ${summary.totalCurators} curators`}
            />
          </div>
        )}

        {/* Disclaimer */}
        <div className="mb-6 p-4 bg-accent-yellow/10 border border-accent-yellow/20 rounded-xl">
          <p className="text-sm text-text-secondary">
            <span className="font-medium text-accent-yellow">Note:</span> These are estimated fees based on current TVL, APY, and fee structures.
            Actual fees depend on realized yields and may vary. Performance fees only accrue when vaults generate positive returns.
          </p>
        </div>

        {/* View Toggle */}
        <div className="flex items-center gap-2 mb-4">
          <span className="text-sm text-text-secondary">View by:</span>
          <div className="flex rounded-lg border border-border overflow-hidden">
            <button
              onClick={() => setViewMode("curators")}
              className={`px-4 py-2 text-sm font-medium transition-colors ${
                viewMode === "curators"
                  ? "bg-accent-blue text-white"
                  : "bg-background-subtle text-text-secondary hover:bg-background-elevated"
              }`}
            >
              Curators
            </button>
            <button
              onClick={() => setViewMode("vaults")}
              className={`px-4 py-2 text-sm font-medium transition-colors ${
                viewMode === "vaults"
                  ? "bg-accent-blue text-white"
                  : "bg-background-subtle text-text-secondary hover:bg-background-elevated"
              }`}
            >
              Vaults
            </button>
          </div>
        </div>

        {/* Curator Fees Grid */}
        {viewMode === "curators" && (
          <CuratorFeesGrid curators={curatorFees} />
        )}

        {/* Vault Fees Grid */}
        {viewMode === "vaults" && (
          <VaultFeesGrid vaults={vaultFees} />
        )}
    </>
  );
}

function SummaryCard({
  label,
  value,
  subtext,
  highlight,
}: {
  label: string;
  value: string;
  subtext: string;
  highlight?: boolean;
}) {
  return (
    <div
      className={`rounded-xl border p-4 ${
        highlight
          ? "border-accent-blue/30 bg-accent-blue/5"
          : "border-border bg-background-subtle"
      }`}
    >
      <p className="text-xs text-text-secondary mb-1">{label}</p>
      <p
        className={`text-2xl font-bold tabular-nums ${
          highlight ? "text-accent-blue" : "text-text-primary"
        }`}
      >
        {value}
      </p>
      <p className="text-xs text-text-tertiary mt-1">{subtext}</p>
    </div>
  );
}
