"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import { formatCurrency, formatPercentage } from "@/lib/utils/format";

interface VaultFeeData {
  vaultId: string;
  vaultAddress: string;
  vaultName: string;
  assetSymbol: string;
  curatorName: string | null;
  curatorAddress: string | null;
  tvl: number;
  apy: number;
  performanceFee: number;
  managementFee: number;
  annualizedCuratorFees: number;
  annualizedMorphoFees: number;
  annualizedTotalFees: number;
}

interface CuratorFeeData {
  curatorId: string;
  curatorName: string;
  curatorAddress: string;
  vaultCount: number;
  totalAUM: number;
  avgPerformanceFee: number;
  avgManagementFee: number;
  annualizedCuratorFees: number;
  annualizedMorphoFees: number;
  annualizedTotalFees: number;
}

interface FeeSummary {
  totalVaults: number;
  totalCurators: number;
  estimated: {
    curatorFees: number;
    morphoFees: number;
    totalFees: number;
  };
  annualized: {
    curatorFees: number;
    morphoFees: number;
    totalFees: number;
  };
}

type ViewMode = "curators" | "vaults";

export default function FeesPage() {
  const [summary, setSummary] = useState<FeeSummary | null>(null);
  const [curatorFees, setCuratorFees] = useState<CuratorFeeData[]>([]);
  const [vaultFees, setVaultFees] = useState<VaultFeeData[]>([]);
  const [loading, setLoading] = useState(true);
  const [viewMode, setViewMode] = useState<ViewMode>("curators");

  useEffect(() => {
    async function fetchData() {
      try {
        const response = await fetch("/api/stats/fees-breakdown");
        const data = await response.json();
        if (data.success) {
          setSummary(data.data.summary);
          setCuratorFees(data.data.byCurator);
          setVaultFees(data.data.byVault);
        }
      } catch (err) {
        console.error("Failed to fetch fees:", err);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-background">
        <Header />
        <main className="max-w-[1400px] mx-auto px-4 sm:px-6 py-6">
          <div className="animate-pulse space-y-4">
            <div className="h-8 w-48 bg-background-elevated rounded" />
            <div className="grid grid-cols-3 gap-4">
              <div className="h-24 bg-background-elevated rounded-xl" />
              <div className="h-24 bg-background-elevated rounded-xl" />
              <div className="h-24 bg-background-elevated rounded-xl" />
            </div>
            <div className="h-64 bg-background-elevated rounded-xl" />
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main className="max-w-[1400px] mx-auto px-4 sm:px-6 py-6">
        {/* Page Title */}
        <div className="mb-6">
          <h1 className="text-2xl font-bold text-text-primary mb-1">Fee Analytics</h1>
          <p className="text-sm text-text-secondary">
            Estimated fees generated by Morpho V2 vaults and curators
          </p>
        </div>

        {/* Summary Cards */}
        {summary && (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
            <SummaryCard
              label="Curator Fees (Annualized)"
              value={formatCurrency(summary.annualized.curatorFees)}
              subtext="Management + Performance"
              highlight
            />
            <SummaryCard
              label="Morpho Protocol Fees (Ann.)"
              value={formatCurrency(summary.annualized.morphoFees)}
              subtext="15% of interest"
            />
            <SummaryCard
              label="Total Fees (Annualized)"
              value={formatCurrency(summary.annualized.totalFees)}
              subtext="All fees combined"
            />
            <SummaryCard
              label="Tracked"
              value={`${summary.totalVaults} vaults`}
              subtext={`from ${summary.totalCurators} curators`}
            />
          </div>
        )}

        {/* Disclaimer */}
        <div className="mb-6 p-4 bg-accent-yellow/10 border border-accent-yellow/20 rounded-xl">
          <p className="text-sm text-text-secondary">
            <span className="font-medium text-accent-yellow">Note:</span> These are estimated fees based on current TVL, APY, and fee structures.
            Actual fees depend on realized yields and may vary. Performance fees only accrue when vaults generate positive returns.
          </p>
        </div>

        {/* View Toggle */}
        <div className="flex items-center gap-2 mb-4">
          <span className="text-sm text-text-secondary">View by:</span>
          <div className="flex rounded-lg border border-border overflow-hidden">
            <button
              onClick={() => setViewMode("curators")}
              className={`px-4 py-2 text-sm font-medium transition-colors ${
                viewMode === "curators"
                  ? "bg-accent-blue text-white"
                  : "bg-background-subtle text-text-secondary hover:bg-background-elevated"
              }`}
            >
              Curators
            </button>
            <button
              onClick={() => setViewMode("vaults")}
              className={`px-4 py-2 text-sm font-medium transition-colors ${
                viewMode === "vaults"
                  ? "bg-accent-blue text-white"
                  : "bg-background-subtle text-text-secondary hover:bg-background-elevated"
              }`}
            >
              Vaults
            </button>
          </div>
        </div>

        {/* Curator Fees Table */}
        {viewMode === "curators" && (
          <div className="bg-background-subtle border border-border rounded-xl overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-border bg-background-elevated/50">
                    <th className="text-left text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      Curator
                    </th>
                    <th className="text-right text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      AUM
                    </th>
                    <th className="text-right text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      Vaults
                    </th>
                    <th className="text-right text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      Avg Perf Fee
                    </th>
                    <th className="text-right text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      Avg Mgmt Fee
                    </th>
                    <th className="text-right text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      Ann. Curator Fees
                    </th>
                    <th className="text-right text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      Ann. Morpho Fees
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {curatorFees.map((curator, index) => (
                    <tr key={curator.curatorId} className="hover:bg-background-elevated/30 transition-colors">
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-3">
                          <span className="text-xs text-text-muted w-5">{index + 1}</span>
                          <div>
                            <p className="font-medium text-text-primary">{curator.curatorName}</p>
                            <p className="text-xs text-text-tertiary font-mono">
                              {curator.curatorAddress.slice(0, 6)}...{curator.curatorAddress.slice(-4)}
                            </p>
                          </div>
                        </div>
                      </td>
                      <td className="text-right px-4 py-3">
                        <span className="font-medium text-text-primary tabular-nums">
                          {formatCurrency(curator.totalAUM)}
                        </span>
                      </td>
                      <td className="text-right px-4 py-3">
                        <span className="text-text-secondary">{curator.vaultCount}</span>
                      </td>
                      <td className="text-right px-4 py-3">
                        <span className="text-text-secondary">
                          {curator.avgPerformanceFee > 0 ? `${curator.avgPerformanceFee.toFixed(1)}%` : "-"}
                        </span>
                      </td>
                      <td className="text-right px-4 py-3">
                        <span className="text-text-secondary">
                          {curator.avgManagementFee > 0 ? `${curator.avgManagementFee.toFixed(2)}%` : "-"}
                        </span>
                      </td>
                      <td className="text-right px-4 py-3">
                        <span className={`font-semibold tabular-nums ${
                          curator.annualizedCuratorFees > 100000 ? "text-accent-green" : "text-text-primary"
                        }`}>
                          {formatCurrency(curator.annualizedCuratorFees)}
                        </span>
                      </td>
                      <td className="text-right px-4 py-3">
                        <span className="text-text-secondary tabular-nums">
                          {formatCurrency(curator.annualizedMorphoFees)}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Vault Fees Table */}
        {viewMode === "vaults" && (
          <div className="bg-background-subtle border border-border rounded-xl overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-border bg-background-elevated/50">
                    <th className="text-left text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      Vault
                    </th>
                    <th className="text-left text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      Curator
                    </th>
                    <th className="text-right text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      TVL
                    </th>
                    <th className="text-right text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      Net APY
                    </th>
                    <th className="text-right text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      Perf Fee
                    </th>
                    <th className="text-right text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      Mgmt Fee
                    </th>
                    <th className="text-right text-xs font-medium text-text-secondary uppercase tracking-wider px-4 py-3">
                      Ann. Curator Fees
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {vaultFees.slice(0, 50).map((vault, index) => (
                    <tr key={vault.vaultId} className="hover:bg-background-elevated/30 transition-colors">
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-3">
                          <span className="text-xs text-text-muted w-5">{index + 1}</span>
                          <div>
                            <Link
                              href={`/vault/${vault.vaultAddress}`}
                              className="font-medium text-text-primary hover:text-accent-blue transition-colors"
                            >
                              {vault.vaultName}
                            </Link>
                            <p className="text-xs text-text-tertiary">{vault.assetSymbol}</p>
                          </div>
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        <span className="text-sm text-text-secondary">{vault.curatorName || "-"}</span>
                      </td>
                      <td className="text-right px-4 py-3">
                        <span className="font-medium text-text-primary tabular-nums">
                          {formatCurrency(vault.tvl)}
                        </span>
                      </td>
                      <td className="text-right px-4 py-3">
                        <span className="text-accent-green tabular-nums">
                          {vault.apy.toFixed(2)}%
                        </span>
                      </td>
                      <td className="text-right px-4 py-3">
                        <span className="text-text-secondary">
                          {vault.performanceFee > 0 ? `${vault.performanceFee.toFixed(0)}%` : "-"}
                        </span>
                      </td>
                      <td className="text-right px-4 py-3">
                        <span className="text-text-secondary">
                          {vault.managementFee > 0 ? `${vault.managementFee.toFixed(2)}%` : "-"}
                        </span>
                      </td>
                      <td className="text-right px-4 py-3">
                        <span className={`font-semibold tabular-nums ${
                          vault.annualizedCuratorFees > 100000 ? "text-accent-green" : "text-text-primary"
                        }`}>
                          {formatCurrency(vault.annualizedCuratorFees)}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </main>

      <footer className="border-t border-border bg-background-subtle mt-auto">
        <div className="max-w-[1400px] mx-auto px-4 sm:px-6 py-4">
          <div className="flex items-center justify-between text-xs text-text-tertiary">
            <p>
              Data from{" "}
              <a href="https://api.morpho.org/graphql" target="_blank" rel="noopener noreferrer" className="text-accent-blue hover:text-accent-blue-hover">Morpho API</a>
              {" "}&bull; Updated hourly
            </p>
            <div className="flex items-center gap-3">
              <Link href="/changelog" className="text-text-tertiary hover:text-text-primary transition-colors">
                Changelog
              </Link>
              <a href="https://x.com/curator_watch" target="_blank" rel="noopener noreferrer" className="text-text-tertiary hover:text-text-primary transition-colors" title="Follow us on X">
                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" /></svg>
              </a>
              <span className="flex items-center gap-1.5">
                <span className="w-1.5 h-1.5 rounded-full bg-accent-green" />
                Live
              </span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}

function Header() {
  return (
    <header className="bg-background-subtle border-b border-border sticky top-0 z-50">
      <div className="max-w-[1400px] mx-auto px-4 sm:px-6 py-3">
        <div className="flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <Image src="/logo.png" alt="CuratorWatch" width={32} height={32} className="rounded-lg" />
            <div>
              <h1 className="text-lg font-bold text-text-primary tracking-tight leading-tight">
                CuratorWatch
              </h1>
              <p className="text-[10px] text-text-tertiary leading-tight">
                Morpho V2 Vault Analytics
              </p>
            </div>
          </Link>
          <nav className="flex items-center gap-5">
            <Link
              href="/"
              className="text-sm text-text-secondary hover:text-text-primary transition-colors"
            >
              Dashboard
            </Link>
            <Link
              href="/vaults"
              className="text-sm text-text-secondary hover:text-text-primary transition-colors"
            >
              Vaults
            </Link>
            <Link
              href="/yields"
              className="text-sm text-text-secondary hover:text-text-primary transition-colors"
            >
              Economics
            </Link>
            <Link href="/fees" className="text-sm font-medium text-accent-blue">
              Fees
            </Link>
            <Link
              href="/alerts"
              className="text-sm text-text-secondary hover:text-text-primary transition-colors"
            >
              Alerts
            </Link>
            <Link
              href="/changelog"
              className="text-sm text-text-secondary hover:text-text-primary transition-colors"
            >
              Changelog
            </Link>
          </nav>
        </div>
      </div>
    </header>
  );
}

function SummaryCard({
  label,
  value,
  subtext,
  highlight,
}: {
  label: string;
  value: string;
  subtext: string;
  highlight?: boolean;
}) {
  return (
    <div
      className={`rounded-xl border p-4 ${
        highlight
          ? "border-accent-blue/30 bg-accent-blue/5"
          : "border-border bg-background-subtle"
      }`}
    >
      <p className="text-xs text-text-secondary mb-1">{label}</p>
      <p
        className={`text-2xl font-bold tabular-nums ${
          highlight ? "text-accent-blue" : "text-text-primary"
        }`}
      >
        {value}
      </p>
      <p className="text-xs text-text-tertiary mt-1">{subtext}</p>
    </div>
  );
}
